CREATE TABLE [EDI].[EDI845_TRANSFER_TMPLT] (
    [Transfer ID]                       INT             NULL,
    [MF Contract Number]                VARCHAR (20)    NOT NULL,
    [Contract Status Code]              CHAR (2)        NULL,
    [Buyer Group Contract Number]       VARCHAR (20)    NULL,
    [MF Contract Name]                  VARCHAR (50)    NULL,
    [Previous Contract Number]          VARCHAR (20)    NULL,
    [Contract Effective Date]           INT             NULL,
    [Contract Expiration Date]          INT             NULL,
    [Replaced Contract Expiration Date] INT             NULL,
    [Contract Tier Number]              INT             NULL,
    [Buyer Group Name]                  VARCHAR (100)   NULL,
    [Eligible Buyer Name]               VARCHAR (150)   NULL,
    [Manufacturer Name]                 VARCHAR (60)    NULL,
    [Buyer Group HIN]                   VARCHAR (60)    NULL,
    [Manufacturer HIN]                  VARCHAR (60)    NULL,
    [Eligible Buyer Account Number]     VARCHAR (60)    NULL,
    [Eligible Buyer GPO Account Number] VARCHAR (60)    NULL,
    [Eligible Buyer Address 1]          VARCHAR (150)   NULL,
    [Eligible Buyer Address 2]          VARCHAR (150)   NULL,
    [Eligible Buyer City]               VARCHAR (100)   NULL,
    [Eligible Buyer State]              VARCHAR (50)    NULL,
    [Eligible Buyer Zip]                VARCHAR (20)    NULL,
    [Eligible Buyer Country Code]       VARCHAR (50)    NULL,
    [Update Reason Code]                VARCHAR (10)    NULL,
    [Eligible Buyer Effective Date]     INT             NULL,
    [Eligible Buyer Expiration Date]    INT             NULL,
    [Item Update Type Code]             VARCHAR (10)    NULL,
    [Item Description]                  VARCHAR (50)    NULL,
    [Manufacturers Item ID]             VARCHAR (20)    NULL,
    [Contract Unit Price]               DECIMAL (18, 2) NULL,
    [Quantity Information]              INT             NULL,
    [Unit of Measure]                   CHAR (2)        NULL,
    [Product Effective Date]            INT             NULL,
    [Product Expiration Date]           INT             NULL,
    [SRC_REC_LST_MOD_DTTM_NR]           BIGINT          NULL,
    [PDI Action Code]                   INT             NOT NULL,
    [Current Timestamp]                 DATETIME        NULL,
    [Orig Contract Expiration Date]     INT             NULL
);

