CREATE TABLE [STG0].[PDI_ASC_Affiliations] (
    [HOSPITAL_ID]                                                     VARCHAR (MAX) NULL,
    [HOSPITAL_NAME]                                                   VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_ID]                                           VARCHAR (50)  NULL,
    [AFFILIATED_ACCOUNT_NAME]                                         VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_FIRM_TYPE]                                    VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_ADDRESS]                                      VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_ADDRESS1]                                     VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_CITY]                                         VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_STATE]                                        VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_ZIP_CODE]                                     VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NETWORK_ID]                                   VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NETWORK_NAME]                                 VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NETWORK_PARENT_ID]                            VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NETWORK_PARENT_NAME]                          VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NPI]                                          VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_PROVIDER_NUMBER]                              VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_ASC_TOTAL_CHARGES]                            VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_ASC_NUMBER_CLAIMS]                            VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NUMBER_HOSPITALS]                             VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_TOTAL_CHARGES]                                VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NET_PATIENT_REVENUE]                          VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_HOSPITAL_OWNERSHIP]                           VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_FINANCIAL_DATA_DATE]                          VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NUMBER_BEDS]                                  VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NUMBER_AFFILIATED_PHYSICIANS]                 VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_NUMBER_AFFILIATED_PHYSICIANS_PHYSICIAN_GROUP] VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_HHA_TOTAL_VISITS]                             VARCHAR (MAX) NULL,
    [AFFILIATED_ACCOUNT_HOSPICE_TOTAL_MEDICARE_CLAIMS]                VARCHAR (MAX) NULL,
    [CURRENT_TIMESTAMP]                                               DATETIME      DEFAULT (getdate()) NOT NULL
);

