CREATE TABLE [STG0].[PDI_MAX_TO_DEFHC_CROSSWALK] (
    [HOSPITAL_ID]       VARCHAR (MAX) NULL,
    [FIRM_TYPE]         VARCHAR (MAX) NULL,
    [COMPANY_ID]        VARCHAR (MAX) NULL,
    [CURRENT_TIMESTAMP] DATETIME      DEFAULT (getdate()) NOT NULL
);

