CREATE TABLE [STG0].[PDI_ASC_Purchasing] (
    [HOSPITAL_ID]       VARCHAR (MAX) NULL,
    [HOAPITAL_NAME]     VARCHAR (MAX) NULL,
    [GPO_ID]            VARCHAR (MAX) NULL,
    [GPO_NAME]          VARCHAR (MAX) NULL,
    [GPO_TYPE]          VARCHAR (MAX) NULL,
    [GPO_HQ_CITY]       VARCHAR (MAX) NULL,
    [GPO_HQ_STATE]      VARCHAR (MAX) NULL,
    [GPO_HQ_PHONE]      VARCHAR (MAX) NULL,
    [GPO_HQ_WEBSITE]    VARCHAR (MAX) NULL,
    [NUM_AFFILIATIONS]  VARCHAR (MAX) NULL,
    [CURRENT_TIMESTAMP] DATETIME      DEFAULT (getdate()) NOT NULL
);

