CREATE TABLE [STG0].[PDI_Hospital_Beds_Breakdown] (
    [HOSPITAL_ID]         VARCHAR (MAX) NULL,
    [HOSPITAL_NAME]       VARCHAR (MAX) NULL,
    [BED_TYPE]            VARCHAR (MAX) NULL,
    [REVENUES]            VARCHAR (MAX) NULL,
    [INPATIENT_REVENUE]   VARCHAR (MAX) NULL,
    [OUTPATIENT_REVENUES] VARCHAR (MAX) NULL,
    [COSTS]               VARCHAR (MAX) NULL,
    [SALARIES]            VARCHAR (MAX) NULL,
    [NUMBER_BEDS]         VARCHAR (MAX) NULL,
    [MEDICARE_DAYS]       VARCHAR (MAX) NULL,
    [MEDICAID_DAYS]       VARCHAR (MAX) NULL,
    [OTHER_DAYS]          VARCHAR (MAX) NULL,
    [TOTAL_DAYS]          VARCHAR (MAX) NULL,
    [BED_DAYS_AVAILABLE]  VARCHAR (MAX) NULL,
    [UTILIZATION_RATE]    VARCHAR (MAX) NULL,
    [CURRENT_TIMESTAMP]   DATETIME      DEFAULT (getdate()) NOT NULL
);

