CREATE TABLE [STG0].[RELATIONSHIP] (
    [COMPANYID]        VARCHAR (MAX) NULL,
    [PARENTCOMPANYID]  VARCHAR (MAX) NULL,
    [RELATIONSHIPTYPE] VARCHAR (MAX) NULL,
    [PARENTIDNCOUNT]   VARCHAR (MAX) NULL,
    [DISTANCETOCHILD]  VARCHAR (MAX) NULL
);

