CREATE TABLE [STG0].[SALES_TRACING_NON_EDI_ETL_N3] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [SALES_PERIOD]      VARCHAR (10)    NULL,
    [YEAR]              CHAR (4)        NULL,
    [MNTH]              CHAR (2)        NULL,
    [DAY]               CHAR (2)        NULL,
    [RPT_DT]            DECIMAL (8)     NULL,
    [DIST_ID]           VARCHAR (48)    NULL,
    [DIST_NR]           VARCHAR (15)    NULL,
    [TRC_TRANS_TYP]     VARCHAR (MAX)   NULL,
    [TRC_CNT_ID]        VARCHAR (MAX)   NULL,
    [TRC_PROD_ID]       VARCHAR (MAX)   NULL,
    [TRC_PRC_TYP]       VARCHAR (MAX)   NULL,
    [INV_ID]            VARCHAR (MAX)   NULL,
    [INV_DT]            VARCHAR (MAX)   NULL,
    [INV_DT_NR]         VARCHAR (MAX)   NULL,
    [TRC_UNIT]          VARCHAR (MAX)   NULL,
    [TRC_QTY_SLD]       VARCHAR (MAX)   NULL,
    [TRC_CNT_PRC]       VARCHAR (MAX)   NULL,
    [TRC_LIST_PRC]      VARCHAR (MAX)   NULL,
    [TRC_DIST_PRC]      VARCHAR (MAX)   NULL,
    [TRC_EXT_LIST_COST] VARCHAR (MAX)   NULL,
    [TRC_EXT_DIST_COST] INT             NULL,
    [TRC_EXT_CNT_COST]  VARCHAR (MAX)   NULL,
    [TRC_RBT_AMT]       VARCHAR (MAX)   NULL,
    [LINE_NR]           VARCHAR (MAX)   NULL,
    [SHPTO_ID]          VARCHAR (MAX)   NULL,
    [SHPTO_NM]          VARCHAR (MAX)   NULL,
    [SHPTO_ADDR_1]      VARCHAR (MAX)   NULL,
    [SHPTO_ADDR_2]      VARCHAR (MAX)   NULL,
    [SHPTO_CITY]        VARCHAR (MAX)   NULL,
    [SHPTO_ST]          VARCHAR (MAX)   NULL,
    [SHPTO_ZIP]         VARCHAR (MAX)   NULL,
    [SHPTO_TYP]         VARCHAR (MAX)   NULL,
    [BILLTO_ID]         VARCHAR (MAX)   NULL,
    [BILLTO_NM]         VARCHAR (MAX)   NULL,
    [BILLTO_ADDR_1]     VARCHAR (MAX)   NULL,
    [BILLTO_ADDR_2]     VARCHAR (MAX)   NULL,
    [BILLTO_CITY]       VARCHAR (MAX)   NULL,
    [BILLTO_ST]         VARCHAR (MAX)   NULL,
    [BILLTO_ZIP]        VARCHAR (MAX)   NULL,
    [BILLTO_TYP]        VARCHAR (MAX)   NULL,
    [DBT_MEMO]          VARCHAR (MAX)   NULL,
    [CURRENT TIMESTAMP] VARCHAR (50)    NOT NULL,
    [TRC_CS_PRC]        DECIMAL (38, 8) NULL,
    [CNT_EXP_DT]        DATE            NULL,
    [TRC_UPDT_UNIT]     CHAR (2)        NULL,
    [TRC_SALES_AMT]     DECIMAL (38, 8) NULL,
    [LIST_CS_PRC]       DECIMAL (38, 4) NULL,
    [TRC_EXT_RBT_AMT]   VARCHAR (MAX)   NULL,
    [TRC_PROD_DESC]     VARCHAR (MAX)   NULL,
    [LOAD_IN]           CHAR (1)        NULL,
    [CH_DIST_ID]        VARCHAR (MAX)   NULL
);

