CREATE TABLE [STG0].[TRC_DDI_CCD] (
    [SALES_PERIOD]      VARCHAR (10)  NULL,
    [DIST_ID]           VARCHAR (48)  NULL,
    [DIST_NR]           VARCHAR (15)  NULL,
    [SHPTO_ID]          VARCHAR (MAX) NULL,
    [SHPTO_NM]          VARCHAR (MAX) NULL,
    [SHPTO_ADDR_1]      VARCHAR (MAX) NULL,
    [SHPTO_ADDR_2]      VARCHAR (MAX) NULL,
    [SHPTO_CITY]        VARCHAR (MAX) NULL,
    [SHPTO_ST]          VARCHAR (MAX) NULL,
    [SHPTO_ZIP]         VARCHAR (MAX) NULL,
    [INV_ID]            VARCHAR (MAX) NULL,
    [INV_DT]            VARCHAR (MAX) NULL,
    [TRC_QTY_SLD]       VARCHAR (MAX) NULL,
    [TRC_LIST_PRC]      VARCHAR (MAX) NULL,
    [TRC_PROD_ID]       VARCHAR (MAX) NULL,
    [TRC_EXT_LIST_COST] VARCHAR (MAX) NULL
);

