CREATE PROCEDURE [TRC].[spLOAD_PROD_CORR_XREF]
WITH EXEC AS CALLER
AS
BEGIN  

  BEGIN
   MERGE [STAGE].[TRC_PROD_CORR_XREF] T
    USING (
      SELECT
      DISTINCT I.DISTCOID, I.DISTID, I.DISTITEMID,  D.COITEMID
    FROM
   STAGE.DDS_PDI_SAF_EXTRACT D
    JOIN (
      SELECT S.DISTCOID, S.DISTID, S.DISTITEMID,  MAX(S.DISTINVOICEDATE ) AS INVDTE
      FROM PDI_SALESTRACING_DEV.STAGE.DDS_PDI_SAF_EXTRACT S
      WHERE LTRIM(RTRIM(COITEMID)) <> LTRIM(RTRIM(DISTITEMID))
      GROUP BY S.DISTCOID, S.DISTID, S.DISTITEMID) I
    ON D.DISTCOID = I.DISTCOID AND I.DISTITEMID = D.DISTITEMID AND I.INVDTE = D.DISTINVOICEDATE 
      ) S ON T.DIST_NR = S.DISTCOID AND T.TRC_PROD_ID = S.DISTITEMID
      
    WHEN NOT MATCHED BY TARGET THEN   -- That means it is a new Contract

      INSERT 
      (DIST_NR, DIST_ID, TRC_PROD_ID, UPD_PROD_ID)
      VALUES
      ( DISTCOID, DISTID, DISTITEMID, COITEMID); 
    END
    
    -- Remove valid product ID - Not sure why those were corrected
    -- Need verification

    DELETE FROM STAGE.TRC_PROD_CORR_XREF
    WHERE TRC_PROD_ID IN (SELECT DISTINCT PRODUCT_ID  FROM PDI_SALESTRACING_DEV.STAGE.DIM_PRODUCT)
    
    -- 'H59200';

END