CREATE PROCEDURE [TRC].[spLOAD_CNT_CORR_XREF]
WITH EXEC AS CALLER
AS
BEGIN  

    TRUNCATE TABLE [STAGE].[TRC_CNT_CORR_XREF];
    
  -- Do not load load any replacement with Tier 2 or above. those canot be applied in general.
  -- In furutre, create a separate table for Hogher tier whihc wil include end user company ID - do it after MDM
  INSERT INTO STAGE.TRC_CNT_CORR_XREF
  ( PROD_ID, TRC_CNT_ID, UPD_CNT_ID,  UPD_CNT_EXP_DT, TRC_CNT_TYP)
  SELECT 
    DISTINCT T.COITEMID, T.DISTCONTID, T.COCONTID, I.LEXP_DT, I.TRC_CNT_TYP
  FROM 
    STAGE.DDS_PDI_SAF_EXTRACT T,
    (
    SELECT COITEMID, DISTCONTID, MAX(C.EXP_DATE) LEXP_DT, 
    CASE WHEN LEFT(DISTCONTID,3) = 'CNT' THEN 'PDI' ELSE 'GPO' END AS TRC_CNT_TYP
    FROM
    STAGE.DDS_PDI_SAF_EXTRACT S
    JOIN STAGE.DIM_CONTRACT C ON S.COCONTID = C.CONTRACT_NO
    WHERE DISTCONTID <> COCONTID --AND C.EXP_DATE > GETDATE()
    --AND ltrim(rtrim(C.TIER_LEVEL)) IN ('1','Tier 1')
    GROUP BY COITEMID, DISTCONTID
    ) I,
    STAGE.DIM_CONTRACT C
  WHERE 
    (T.COITEMID = I.COITEMID AND T.DISTCONTID = I.DISTCONTID )
    AND (T.COCONTID = C.CONTRACT_NO AND I.LEXP_DT = C.EXP_DATE)
    AND T.DISTCONTID <> T.COCONTID
    --AND ltrim(rtrim(C.TIER_LEVEL)) IN ('1','Tier 1')

END