CREATE PROCEDURE [TRC].[spTRC_SAVE_UPI_CORR]
@vDIST_NR varchar(20), @vDIST_ID varchar(30), @vTRC_PROD_ID varchar(30), @vUPD_PROD_ID varchar(30) 
WITH EXEC AS CALLER
AS
BEGIN

  BEGIN
    MERGE [PDI_SALESTRACING_DEV].[STAGE].[TRC_PROD_CORR_XREF] T
      USING
        (SELECT 
          DIST_NR = @vDIST_NR,  DIST_ID=@vDIST_ID, TRC_PROD_ID = @vTRC_PROD_ID, UPD_PROD_ID=@vUPD_PROD_ID
        ) AS S 
        ON T.DIST_NR = S.DIST_NR AND T.TRC_PROD_ID = S.TRC_PROD_ID
      
      WHEN NOT MATCHED BY TARGET THEN
      INSERT 
        (DIST_NR, DIST_ID, TRC_PROD_ID, UPD_PROD_ID)
      VALUES
        (S.DIST_NR, S.DIST_ID, S.TRC_PROD_ID, S.UPD_PROD_ID)
      
      WHEN MATCHED THEN
      UPDATE 
        SET T.UPD_PROD_ID = S.UPD_PROD_ID;
      
  END;

END