CREATE PROCEDURE [TRC].[spTRC_GET_ERR_UPI]
@vSales_Period varchar(10), @vDIST_ID varchar(20) = null
WITH EXEC AS CALLER
AS
BEGIN

SELECT DISTINCT DIST_ID, DIST_NR, SALES_PERIOD, TRC_PROD_ID as PROD_ID
, L.LKUP_CD_DES as Err_Desc
FROM [PDI_SALESTRACING_DEV].[STAGE].[SALES_TRACING_CURR] S
JOIN PDI_SALESTRACING_DEV.REF.LKUP_CD L ON S.ERR_CD = L.LKUP_CD AND L.LKUP_DOMAIN_CD = 'SLS_TRC_CALC' AND L.CD_TYP = 'ERROR'
WHERE S.Err_Cd = 'UPI'
AND S.SALES_PERIOD = isnull(@vSales_Period,S.SALES_PERIOD) 
AND S.DIST_ID = isnull(@vDIST_ID,S.DIST_ID)


END