CREATE PROCEDURE [TRC].[spTRC_GET_DIST_TREND]
@vSALES_PERIOD varchar(10), @vDist_NR as varchar(20)
WITH EXEC AS CALLER
AS
BEGIN

  DECLARE @vSalesPriod_DT varchar(20), @vSales_Avg int;
  
  SET @vSalesPriod_DT = LEFT(@vSALES_PERIOD,4)+'-'+LEFT(RIGHT(@vSALES_PERIOD,4),2)+'-'+RIGHT(@vSALES_PERIOD,2);
  
  SELECT @vSales_Avg = SALES_AMT_6MO_AVG FROM STAGE.DATA_LOAD_SUMMARY WHERE DIST_NR = @vDist_NR AND SALESPERIOD = @vSALES_PERIOD;
  
SELECT S.DISTID, replace(convert(char(10),(S.SALES_PERIOD_DT)),'-','') as SALES_PERIOD_DT, convert(INT,S.SALES_AMT) AS SALES_AMT,  @vSales_Avg AS SALES_AVG
FROM STAGE.DATA_LOAD_SUMMARY S
WHERE SALES_PERIOD_DT BETWEEN DATEADD(m,-5,CONVERT(DATE,@vSalesPriod_DT )) AND CONVERT(DATE,@vSalesPriod_DT)  
  AND DIST_NR = @vDist_NR
ORDER BY 2 DESC
 

END
