CREATE PROCEDURE [TRC].[spTRC_GET_CURR_MNTH]
@vSALES_PERIOD varchar(10), @vSLS_PERIOD_TYP varchar(20),
@currSALES_PERIOD varchar(10) output, @currDSPLY_NM varchar(20) output
WITH EXEC AS CALLER
AS
BEGIN

  SELECT @currSALES_PERIOD = A.SLS_PERIOD, @currDSPLY_NM = A.SLS_PERIOD_DSPLY_NM
  FROM TRC.SALES_PERIOD_ADMIN A
  WHERE A.SLS_PERIOD_TYP = 'CURRENT';

  SELECT 
    D.DIST_ID, D.DIST_TRC_NM, D.SALES_PERIOD, 
    MAX(D.RECVD_DTE) AS RECVD_DTE, 
    D.LOAD_STAT, 
    format(SUM(D.REC_CNT), 'N0') AS REC_CNT, 
    SUM(D.REC_CNT_CALC) AS REC_CNT_CALC, 
    format(SUM(D.EXCP_COUNT), 'N0') as EXCP_COUNT, 
    format(SUM(D.CS_QTY), 'N0')as CS_QTY , 
    format(D.ROLLING_6_MN_AV_QTY, 'N0') as ROLLING_6_MN_AV_QTY,
    format(D.ROLLING_12_MN_AV_QTY , 'N0') as ROLLING_12_MN_AV_QTY , 
    format(SUM(D.SALES_AMT), 'N0') as SALES_AMT, 
    format(D.ROLLING_6_MN_AV_AMT, 'N0') as ROLLING_6_MN_AV_AMT, 
    format(D.ROLLING_12_MN_AV_AMT, 'N0') as ROLLING_12_MN_AV_AMT
   , d.PROC_STAT,D.SRC_FILE_TYP , A.SLS_PERIOD_DSPLY_NM 
  FROM [STAGE].[SLS_TRC_LOAD_DTL] D
  JOIN TRC.SALES_PERIOD_ADMIN A ON D.SALES_PERIOD = A.SLS_PERIOD
 WHERE A.SLS_PERIOD_TYP = ISNULL(@vSLS_PERIOD_TYP,A.SLS_PERIOD_TYP)
AND D.SALES_PERIOD = ISNULL(@vSALES_PERIOD,D.SALES_PERIOD)
  GROUP BY
    D.DIST_ID, D.DIST_TRC_NM, D.SALES_PERIOD, 
    D.LOAD_STAT,  D.ROLLING_6_MN_AV_QTY, D.ROLLING_12_MN_AV_QTY, 
    D.ROLLING_6_MN_AV_AMT, D.ROLLING_12_MN_AV_AMT, 
    D.PROC_STAT, D.SRC_FILE_TYP , A.SLS_PERIOD_DSPLY_NM 
  ORDER BY SUM(D.SALES_AMT) desc -- CONVERT(INT,D.SALES_AMT)  DESC
  
END