CREATE PROCEDURE [TRC].[spTRC_CALC_CURR_MONTH_SUMMARY] 
( @UNM VARCHAR(20))
WITH EXEC AS CALLER
AS
BEGIN

DECLARE @CNT_NR VARCHAR(20);
DECLARE @RecCnt int;

SELECT DIST_ID, DIST_TRC_NM,SALES_PERIOD,  MAX(RECVD_DTE) LAST_RCV_DT,  SUM(REC_CNT) as TOT_REC
FROM
[PDI_SALESTRACING_DEV].[TRC].[SLS_TRC_LOAD_DTL] S
JOIN [PDI_SALESTRACING_DEV].[TRC].[SALES_PERIOD_ADMIN] A ON S.SALES_PERIOD = A.SLS_PERIOD
WHERE A.SLS_PERIOD_TYP = 'CURRENT'
GROUP BY
DIST_ID, DIST_TRC_NM,SALES_PERIOD


END