
CREATE Proc tree
AS 

WITH tr AS 
(SELECT IDN_CMPNY_ID,IDN_PRNT_CMPNY_ID,CMPNY_ID ,0 as prnt
FROM cmpny.COmpany
UNION ALL
SELECT  c.IDN_CMPNY_ID,c.IDN_PRNT_CMPNY_ID,c.CMPNY_ID , p.prnt +1
FROM cmpny.COmpany c
INNER JOIN tr as p
ON p.IDN_PRNT_CMPNY_ID = c.CMPNY_ID
WHERE c.CMPNY_ID IS NOT NULL)

SELECT * FROM tr as l
ORDER BY prnt