CREATE TABLE [STAGE].[20181101] (
    [COITEMCOST]   VARCHAR (50) NULL,
    [UPD_CS_PRC]   VARCHAR (50) NULL,
    [COITEMID]     VARCHAR (50) NULL,
    [COCONTID]     VARCHAR (50) NULL,
    [trc_cnt_id]   VARCHAR (50) NULL,
    [UPD_CNT_ID]   VARCHAR (50) NULL,
    [SALES_PERIOD] VARCHAR (50) NULL,
    [dist_nr]      VARCHAR (50) NULL,
    [dist_id]      VARCHAR (50) NULL,
    [DISTID]       VARCHAR (50) NULL
);

