CREATE TABLE [STAGE].[CMS_DATALOAD] (
    [NPI]                                                                        INT           NULL,
    [Entity Type Code]                                                           NVARCHAR (50) NULL,
    [Replacement NPI]                                                            NVARCHAR (50) NULL,
    [Employer Identification Number (EIN)]                                       NVARCHAR (50) NULL,
    [Provider Organization Name (Legal Business Name)]                           NVARCHAR (76) NULL,
    [Provider Last Name (Legal Name)]                                            NVARCHAR (50) NULL,
    [Provider First Name]                                                        NVARCHAR (50) NULL,
    [Provider Middle Name]                                                       NVARCHAR (50) NULL,
    [Provider Credential Text]                                                   NVARCHAR (50) NULL,
    [Provider Other Organization Name]                                           NVARCHAR (85) NULL,
    [Provider Other Organization Name Type Code]                                 NVARCHAR (50) NULL,
    [Provider First Line Business Mailing Address]                               NVARCHAR (60) NULL,
    [Provider Second Line Business Mailing Address]                              NVARCHAR (67) NULL,
    [Provider Business Mailing Address City Name]                                NVARCHAR (50) NULL,
    [Provider Business Mailing Address State Name]                               NVARCHAR (50) NULL,
    [Provider Business Mailing Address Postal Code]                              NVARCHAR (50) NULL,
    [Provider Business Mailing Address Country Code (If outside U.S.)]           NVARCHAR (50) NULL,
    [Provider First Line Business Practice Location Address]                     NVARCHAR (60) NULL,
    [Provider Second Line Business Practice Location Address]                    NVARCHAR (67) NULL,
    [Provider Business Practice Location Address City Name]                      NVARCHAR (50) NULL,
    [Provider Business Practice Location Address State Name]                     NVARCHAR (50) NULL,
    [Provider Business Practice Location Address Postal Code]                    NVARCHAR (50) NULL,
    [Provider Business Practice Location Address Country Code (If outside U.S.)] NVARCHAR (50) NULL,
    [Last Update Date]                                                           NVARCHAR (50) NULL,
    [NPI Deactivation Reason Code]                                               NVARCHAR (50) NULL,
    [NPI Deactivation Date]                                                      NVARCHAR (50) NULL,
    [NPI Reactivation Date]                                                      NVARCHAR (50) NULL
);

