CREATE TABLE [STAGE].[COMPANY_EU_1K] (
    [DISTCOID]          VARCHAR (20)    NULL,
    [DISTID]            VARCHAR (8)     NULL,
    [DISTACCTID]        VARCHAR (20)    NULL,
    [DISTACCTSHIPNAME]  VARCHAR (50)    NULL,
    [DISTACCTSHIPADDR1] VARCHAR (50)    NULL,
    [DISTACCTSHIPADDR2] VARCHAR (50)    NULL,
    [DISTACCTSHIPCITY]  VARCHAR (50)    NULL,
    [DISTACCTSHIPSTATE] VARCHAR (2)     NULL,
    [DISTACCTSHIPZIP]   VARCHAR (10)    NULL,
    [COACCTID]          VARCHAR (20)    NULL,
    [COACCTMAX]         VARCHAR (20)    NULL,
    [SALES_SUM]         NUMERIC (38, 2) NULL,
    [ADDR1_NBR]         VARCHAR (200)   NULL,
    [ADDR1_ST]          VARCHAR (200)   NULL,
    [ADDR2_1]           VARCHAR (40)    NULL,
    [ADDR2_2]           VARCHAR (200)   NULL,
    [ISSUE]             VARCHAR (20)    NULL
);

