CREATE TABLE [STAGE].[CROTHALL_GAP_ANALYSIS] (
    [YR_MN]            VARCHAR (6)      NULL,
    [ENDUSER_ID]       VARCHAR (150)    NULL,
    [ENDUSER_NAME]     VARCHAR (150)    NULL,
    [COACCTID]         VARCHAR (20)     NULL,
    [COACCTMAX]        VARCHAR (20)     NULL,
    [ADDR1]            VARCHAR (250)    NULL,
    [ADDR2]            VARCHAR (250)    NULL,
    [CITY]             VARCHAR (50)     NULL,
    [ST]               VARCHAR (2)      NULL,
    [ZIP]              VARCHAR (10)     NULL,
    [CNT_NR]           VARCHAR (30)     NULL,
    [PROD_ID]          VARCHAR (30)     NULL,
    [SLS_2018]         NUMERIC (38, 2)  NULL,
    [MonthYear]        INT              NULL,
    [EndUser ID]       INT              NULL,
    [EndUser Name]     NVARCHAR (95)    NULL,
    [ShipTo Address1]  NVARCHAR (66)    NULL,
    [ShipTo City]      NVARCHAR (50)    NULL,
    [Shipto State]     NVARCHAR (50)    NULL,
    [ShipTo Zip]       NVARCHAR (50)    NULL,
    [Distributor Name] NVARCHAR (59)    NULL,
    [Contract Name]    NVARCHAR (50)    NULL,
    [Contract Number]  NVARCHAR (50)    NULL,
    [Product ID]       NVARCHAR (50)    NULL,
    [Sales Amount]     DECIMAL (28, 10) NULL
);

