CREATE TABLE [STAGE].[DHC_COMPANY] (
    [DHC_CO_ID]           INT           NOT NULL,
    [DHC_CO_NM_1]         VARCHAR (255) NULL,
    [DHC_CO_NM_2]         VARCHAR (255) NULL,
    [DHC_CO_NM_2_TYP]     VARCHAR (20)  NULL,
    [DHC_CO_ADDR_1]       VARCHAR (255) NULL,
    [DHC_CO_ADDR_2]       VARCHAR (255) NULL,
    [DHC_CO_CITY]         VARCHAR (255) NULL,
    [UPDT_CO_CITY]        VARCHAR (50)  NULL,
    [DHC_CO_ST]           CHAR (2)      NULL,
    [DHC_CO_ZIP]          VARCHAR (10)  NOT NULL,
    [DHC_CO_CNTRY]        CHAR (3)      NULL,
    [DHC_CO_CAT_CD]       VARCHAR (50)  NULL,
    [DHC_CO_SUB_CAT]      VARCHAR (255) NULL,
    [DHC_NTWRK_ID]        INT           NULL,
    [DHC_NTWRK_PARENT_ID] INT           NULL,
    [HSPTL_PARENT_ID]     INT           NULL,
    [DHC_CO_WEBSITE]      VARCHAR (255) NULL,
    [NPI_NR]              VARCHAR (50)  NULL,
    [GLN_NR]              VARCHAR (50)  NULL,
    [HIN_NR]              VARCHAR (50)  NULL,
    [DEA_NR]              VARCHAR (50)  NULL,
    [DHC_STAT]            VARCHAR (20)  NULL,
    [ISSUE_FLG]           VARCHAR (20)  NULL,
    [DHC_CNTY]            VARCHAR (40)  NULL,
    [UNIQ_FLAG]           SMALLINT      NULL,
    [MFP_FLAG]            SMALLINT      NULL,
    [ORIG_NM]             VARCHAR (255) NULL,
    [ORIG_ADDR1]          VARCHAR (200) NULL,
    [ORIG_ADDR2]          VARCHAR (100) NULL,
    [UPD_NM]              VARCHAR (255) NULL,
    [UPD_ADDR1]           VARCHAR (200) NULL,
    [UPD_ADDR2]           VARCHAR (100) NULL,
    [MATCH_MTHD_cd]       VARCHAR (10)  NULL
);

