CREATE TABLE [STAGE].[DIM_PRODUCT] (
    [PRODUCT_KEY]               INT           NOT NULL,
    [COMPANY_ID]                CHAR (3)      NOT NULL,
    [COMPANY_NAME]              VARCHAR (100) NOT NULL,
    [DIV_ID]                    CHAR (4)      NOT NULL,
    [PRODUCT_ID]                VARCHAR (15)  NOT NULL,
    [PROD_DESC_ERP]             VARCHAR (255) NOT NULL,
    [PROD_EXTRA_DESC_ERP]       VARCHAR (255) NULL,
    [PROD_CATEGORY_SALES]       VARCHAR (100) NOT NULL,
    [PROD_CATEGORY_SALES_SORT]  INT           NOT NULL,
    [PROD_CATEGORY_ERP]         VARCHAR (100) NOT NULL,
    [PROD_CATEGORY_ERP_SORT]    INT           NOT NULL,
    [PROD_CATEGORY_MKT]         VARCHAR (100) NOT NULL,
    [PROD_CATEGORY_MKT_SORT]    INT           NOT NULL,
    [PROD_BRAND]                VARCHAR (100) NOT NULL,
    [PROD_BRAND_SORT]           INT           NOT NULL,
    [SALES_TYPE]                VARCHAR (100) NOT NULL,
    [NEW_PRODUCT_INDICATOR_Y_N] CHAR (4)      NOT NULL,
    [CURRENT_INDICATOR_Y_N]     CHAR (2)      NOT NULL,
    [SELL_UOM]                  CHAR (3)      NOT NULL,
    [BPCS_CREATE_DATE]          VARCHAR (10)  NULL,
    [BPCS_LAST_MAINT_DATE]      VARCHAR (10)  NULL,
    [EFFECTIVE_DATE]            VARCHAR (10)  NULL,
    [EXPIRATION_DATE]           VARCHAR (10)  NOT NULL,
    [REPORT_SORTORDER]          INT           NULL,
    [ETL_AUDIT_KEY]             BIGINT        NULL,
    [CURRENT TIMESTAMP]         VARCHAR (50)  NOT NULL
);

