CREATE TABLE [STAGE].[DIM_DISTRIBUTOR] (
    [DIST_KEY]                      SMALLINT      NOT NULL,
    [COMPANY_ID]                    CHAR (3)      NOT NULL,
    [TRACING_NAME]                  VARCHAR (30)  NOT NULL,
    [DIV_ID]                        CHAR (4)      NOT NULL,
    [DIST_ID]                       VARCHAR (15)  NOT NULL,
    [DIST_NAME]                     VARCHAR (100) NOT NULL,
    [DIST_PARENT_NAME]              VARCHAR (100) NOT NULL,
    [DIST_TOP_PARENT_NAME]          VARCHAR (100) NOT NULL,
    [DIST_SALES_TYPE]               VARCHAR (100) NOT NULL,
    [DIST_PRICING_PARENT_ID]        INT           NOT NULL,
    [DIST_PRICING_PARENT_NAME]      VARCHAR (100) NOT NULL,
    [DIST_ADDR1]                    VARCHAR (100) NULL,
    [DIST_ADDR2]                    VARCHAR (100) NULL,
    [DIST_CITY]                     VARCHAR (100) NULL,
    [DIST_STATE]                    CHAR (2)      NULL,
    [DIST_ZIPCODE]                  VARCHAR (10)  NULL,
    [DIST_COUNTRYCODE]              CHAR (3)      NULL,
    [DIST_COUNTRYNAME]              VARCHAR (100) NULL,
    [CURRENT_INDICATOR_Y_N]         CHAR (1)      NOT NULL,
    [COMPLERE_RECORD_INDICATOR_Y_N] CHAR (1)      NOT NULL,
    [EFFECTIVE_DATE]                DATE          NOT NULL,
    [EXPIRATION_DATE]               DATE          NOT NULL,
    [UPDATED_BY]                    VARCHAR (20)  NOT NULL,
    [MAJOR_LTC_INDICATOR]           CHAR (1)      NULL,
    [MARKET_SEGMENT]                VARCHAR (50)  NULL,
    [DATASOURCE]                    VARCHAR (20)  NULL,
    [ETL_AUDIT_KEY]                 INT           NULL,
    [CURRENT TIMESTAMP]             DATETIME      NOT NULL
);

