CREATE TABLE [STAGE].[MedlineVDR$] (
    [Vendor]        FLOAT (53)     NULL,
    [MedlineCon]    NVARCHAR (255) NULL,
    [VendorCont]    NVARCHAR (255) NULL,
    [GPO ID]        NVARCHAR (255) NULL,
    [Invoice]       FLOAT (53)     NULL,
    [Line]          FLOAT (53)     NULL,
    [InvoiceDat]    FLOAT (53)     NULL,
    [VendorItm]     NVARCHAR (255) NULL,
    [MedlineItm]    NVARCHAR (255) NULL,
    [Material GTIN] NVARCHAR (255) NULL,
    [Customer]      FLOAT (53)     NULL,
    [CustName]      NVARCHAR (255) NULL,
    [CustStreet]    NVARCHAR (255) NULL,
    [CustCity]      NVARCHAR (255) NULL,
    [CustState]     NVARCHAR (255) NULL,
    [CustZipcod]    NVARCHAR (255) NULL,
    [Sold-To DEA#]  NVARCHAR (255) NULL,
    [Sold-To GLN]   NVARCHAR (255) NULL,
    [VendItmDes]    NVARCHAR (255) NULL,
    [DocType]       NVARCHAR (255) NULL,
    [Quantity]      FLOAT (53)     NULL,
    [UoM]           NVARCHAR (255) NULL,
    [Plant]         NVARCHAR (255) NULL,
    [PlantStreet]   NVARCHAR (255) NULL,
    [PlantAddress]  NVARCHAR (255) NULL,
    [AcqCost]       FLOAT (53)     NULL,
    [RebateAmt]     FLOAT (53)     NULL,
    [ContrCost]     FLOAT (53)     NULL,
    [PremiumAmt]    FLOAT (53)     NULL,
    [PremiumPct]    FLOAT (53)     NULL,
    [CondPrcUni]    FLOAT (53)     NULL,
    [CondUnitDo]    NVARCHAR (255) NULL,
    [ContDisc]      FLOAT (53)     NULL,
    [CustGrp]       NVARCHAR (255) NULL,
    [Debit Memo]    FLOAT (53)     NULL,
    [ ]             NVARCHAR (255) NULL
);

