CREATE TABLE [STAGE].[PDI_Hospital_Overview] (
    [HOSPITAL_ID]                        INT           NULL,
    [HOSPITAL_NAME]                      VARCHAR (MAX) NULL,
    [PROVIDER_NUMBER]                    VARCHAR (MAX) NULL,
    [FIRM_TYPE]                          VARCHAR (MAX) NULL,
    [HOSPITAL_TYPE]                      VARCHAR (MAX) NULL,
    [HQ_ADDRESS]                         VARCHAR (MAX) NULL,
    [HQ_ADDRESS1]                        VARCHAR (MAX) NULL,
    [HQ_CITY]                            VARCHAR (MAX) NULL,
    [HQ_STATE]                           VARCHAR (MAX) NULL,
    [HQ_ZIP_CODE]                        INT           NULL,
    [HQ_COUNTY]                          VARCHAR (MAX) NULL,
    [CBSA_CODE_DESCRIPTION]              VARCHAR (MAX) NULL,
    [CBSA_POPULATION_EST_MOST_RECENT]    INT           NULL,
    [CBSA_POPULATION_GROWTH_MOST_RECENT] VARCHAR (MAX) NULL,
    [WEBSITE]                            VARCHAR (MAX) NULL,
    [NETWORK_ID]                         VARCHAR (MAX) NULL,
    [NETWORK_NAME]                       VARCHAR (MAX) NULL,
    [NETWORK_PARENT_ID]                  VARCHAR (MAX) NULL,
    [NETWORK_PARENT_NAME]                VARCHAR (MAX) NULL,
    [NPI_NUMBER]                         INT           NULL,
    [PROGRAM_340B_ID]                    VARCHAR (MAX) NULL,
    [HIN]                                VARCHAR (MAX) NULL,
    [GLN]                                VARCHAR (MAX) NULL,
    [DEA_REGISTRATION_NUMBER]            VARCHAR (MAX) NULL,
    [MEDICAL_SCHOOL_AFFILIATION]         VARCHAR (MAX) NULL,
    [ACCREDITATION_AGENCY]               VARCHAR (MAX) NULL,
    [HOSPITAL_OWNERSHIP]                 VARCHAR (MAX) NULL,
    [MEDICARE_ADMINISTRATIVE_CONTRACTOR] VARCHAR (MAX) NULL,
    [FINANCIAL_DATA_DATE]                DATETIME2 (7) NULL
);

