CREATE TABLE [STAGE].[PDI_RELATIONSHIP_FILE] (
    [COMPANYID]        INT           NULL,
    [PARENTCOMPANYID]  INT           NULL,
    [RELATIONSHIPTYPE] VARCHAR (MAX) NULL,
    [PARENTIDNCOUNT]   INT           NULL,
    [DISTANCETOCHILD]  FLOAT (53)    NULL,
    [HOSPITAL_ID]      VARCHAR (MAX) NULL
);

