CREATE TABLE [STAGE].[PDI_LTC_SNF_Overview] (
    [HOSPITAL_ID]                        INT            NULL,
    [HOSPITAL_NAME]                      VARCHAR (MAX)  NULL,
    [HQ_ADDRESS]                         VARCHAR (MAX)  NULL,
    [HQ_ADDRESS1]                        VARCHAR (MAX)  NULL,
    [HQ_CITY]                            VARCHAR (MAX)  NULL,
    [HQ_STATE]                           VARCHAR (MAX)  NULL,
    [HQ_ZIP_CODE]                        INT            NULL,
    [HQ_LATITUDE]                        FLOAT (53)     NULL,
    [HQ_LONGITUDE]                       FLOAT (53)     NULL,
    [WEBSITE]                            VARCHAR (MAX)  NULL,
    [HQ_COUNTY]                          VARCHAR (MAX)  NULL,
    [CRM_INTEGRATION_LINK]               VARCHAR (MAX)  NULL,
    [HQ_PHONE]                           VARCHAR (MAX)  NULL,
    [NETWORK_ID]                         INT            NULL,
    [NETWORK_NAME]                       VARCHAR (MAX)  NULL,
    [NETWORK_PARENT_ID]                  VARCHAR (MAX)  NULL,
    [NETWORK_PARENT_NAME]                VARCHAR (MAX)  NULL,
    [HOSPITAL_PARENT_ID]                 VARCHAR (MAX)  NULL,
    [HOSPITAL_PARENT_NAME]               VARCHAR (MAX)  NULL,
    [PG_PARENT_ID]                       VARCHAR (MAX)  NULL,
    [CBSA_CODE]                          NVARCHAR (100) NULL,
    [CBSA_POPULATION_EST_MOST_RECENT]    INT            NULL,
    [CBSA_POPULATION_GROWTH_MOST_RECENT] VARCHAR (MAX)  NULL,
    [FIRM_TYPE]                          VARCHAR (MAX)  NULL,
    [NPI_NUMBER]                         VARCHAR (MAX)  NULL,
    [PROVIDER_NUMBER]                    VARCHAR (MAX)  NULL,
    [NUMBER_BEDS]                        INT            NULL,
    [FINANCIAL_DATA_DATE]                VARCHAR (MAX)  NULL,
    [DATE_FISCAL_YEAR_END]               VARCHAR (MAX)  NULL,
    [NUMBER_BEDS_MEDICARE]               INT            NULL,
    [HOSPITAL_OWNERSHIP]                 VARCHAR (MAX)  NULL,
    [SNF_CERTIFICATION]                  VARCHAR (MAX)  NULL,
    [SNF_CERTIFICATION_DATE]             VARCHAR (MAX)  NULL,
    [NUMBER_HOSPITALS]                   INT            NULL,
    [BPCI_MODEL]                         VARCHAR (MAX)  NULL,
    [COMPANY_STATUS]                     VARCHAR (MAX)  NULL,
    [ACO_NAME_FOR_EXPORT]                VARCHAR (MAX)  NULL,
    [GPO_NAME_FOR_EXPORT]                VARCHAR (MAX)  NULL,
    [CIN_AFFILIATIONS]                   VARCHAR (MAX)  NULL,
    [HIE_AFFILIATIONS]                   VARCHAR (MAX)  NULL
);

