CREATE TABLE [STAGE].[PDI_ASC_Purchasing] (
    [HOSPITAL_ID]      INT           NULL,
    [HOSPITAL_NAME]    VARCHAR (MAX) NULL,
    [GPO_ID]           INT           NULL,
    [GPO_NAME]         VARCHAR (MAX) NULL,
    [GPO_TYPE]         VARCHAR (MAX) NULL,
    [GPO_HQ_CITY]      VARCHAR (MAX) NULL,
    [GPO_HQ_STATE]     VARCHAR (MAX) NULL,
    [GPO_HQ_PHONE]     VARCHAR (MAX) NULL,
    [GPO_HQ_WEBSITE]   VARCHAR (MAX) NULL,
    [NUM_AFFILIATIONS] INT           NULL
);

