CREATE TABLE [STAGE].[PDI_LTC_LTC_Referrals_From_Physicians] (
    [HOSPITAL_ID]                       INT           NULL,
    [HOSPITAL_NAME]                     VARCHAR (MAX) NULL,
    [NPI]                               INT           NULL,
    [LAST_NAME]                         VARCHAR (MAX) NULL,
    [FIRST_NAME]                        VARCHAR (MAX) NULL,
    [SPECIALTY_PRIMARY]                 VARCHAR (MAX) NULL,
    [HQ_CITY]                           VARCHAR (MAX) NULL,
    [HQ_STATE]                          VARCHAR (MAX) NULL,
    [PRIMARY_AFFILIATION_HOSPITAL_ID]   INT           NULL,
    [PRIMARY_AFFILIATION_HOSPITAL_NAME] VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS30]                 VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS30]                 VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS30]             VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS60]                 VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS60]                 VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS60]             VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS90]                 VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS90]                 VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS90]             VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS180]                VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS180]                VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS180]            VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS30_PY]              VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS30_PY]              VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS30_PY]          VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS60_PY]              VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS60_PY]              VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS60_PY]          VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS90_PY]              INT           NULL,
    [BENE_COUNT_DAYS90_PY]              INT           NULL,
    [SAME_DAY_COUNT_DAYS90_PY]          INT           NULL,
    [PAIR_COUNT_DAYS180_PY]             INT           NULL,
    [BENE_COUNT_DAYS180_PY]             INT           NULL,
    [SAME_DAY_COUNT_DAYS180_PY]         INT           NULL,
    [PAIR_COUNT_DAYS30_PY2]             VARCHAR (MAX) NULL,
    [BENE_COUNT_DAYS30_PY2]             VARCHAR (MAX) NULL,
    [SAME_DAY_COUNT_DAYS30_PY2]         VARCHAR (MAX) NULL,
    [PAIR_COUNT_DAYS60_PY2]             INT           NULL,
    [BENE_COUNT_DAYS60_PY2]             INT           NULL,
    [SAME_DAY_COUNT_DAYS60_PY2]         INT           NULL,
    [PAIR_COUNT_DAYS90_PY2]             INT           NULL,
    [BENE_COUNT_DAYS90_PY2]             INT           NULL,
    [SAME_DAY_COUNT_DAYS90_PY2]         INT           NULL,
    [PAIR_COUNT_DAYS180_PY2]            INT           NULL,
    [BENE_COUNT_DAYS180_PY2]            INT           NULL,
    [SAME_DAY_COUNT_DAYS180_PY2]        INT           NULL
);

