CREATE TABLE [STAGE].[PRC_AUTH_PHASE_2] (
    [PRC_AUTH_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [GPO_ID]        VARCHAR (50) NULL,
    [GPO_MMBR_ID]   VARCHAR (50) NULL,
    [EU_ID]         VARCHAR (50) NULL,
    [PDI_CNT_NR]    VARCHAR (50) NULL,
    [GPO_CNT_NR]    VARCHAR (50) NULL,
    [TIER_NR]       SMALLINT     NULL,
    [ACTVN_DT]      DATE         NULL,
    [PRIM_DIST_ID]  VARCHAR (50) NULL,
    [LAST_MOD_DT]   DATETIME     NULL,
    [SENT_TO_EDI]   BIT          NULL,
    [TRANSFER_STAT] CHAR (1)     NULL,
    CONSTRAINT [PK_PRC_AUTH] PRIMARY KEY CLUSTERED ([PRC_AUTH_ID] ASC) WITH (FILLFACTOR = 100)
);

