CREATE TABLE [STAGE].[PRC_AUTH_EB] (
    [PRC_AUTH_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [PDI_GPO_ID]        INT           NULL,
    [GPO_NM]            VARCHAR (MAX) NULL,
    [GPO_MBR_ID]        VARCHAR (MAX) NULL,
    [GPO_MBR_NM]        VARCHAR (MAX) NULL,
    [GPO_MBR_ADDR1]     VARCHAR (MAX) NULL,
    [GPO_MBR_ADDR2]     VARCHAR (MAX) NULL,
    [GPO_MBR_CITY]      VARCHAR (MAX) NULL,
    [GPO_MBR_ST]        VARCHAR (MAX) NULL,
    [GPO_MBR_ZIP]       VARCHAR (MAX) NULL,
    [GPO_CNT_NR]        VARCHAR (MAX) NULL,
    [MFG_CNT_NR]        VARCHAR (MAX) NULL,
    [TIER_NR]           VARCHAR (MAX) NULL,
    [PRC_EFF_DT]        VARCHAR (MAX) NULL,
    [PRC_EXP_DT]        VARCHAR (MAX) NULL,
    [PRC_ACT_NR]        VARCHAR (50)  NULL,
    [PRC_ACT_DT]        VARCHAR (MAX) NULL,
    [LIC_NR]            VARCHAR (MAX) NULL,
    [STATUS]            VARCHAR (MAX) NULL,
    [SRC_REC_ID]        VARCHAR (MAX) NULL,
    [DEA]               VARCHAR (MAX) NULL,
    [GLN]               VARCHAR (MAX) NULL,
    [HIN]               VARCHAR (MAX) NULL,
    [SEGMENT]           VARCHAR (MAX) NULL,
    [REC_STAT_CD]       CHAR (1)      NULL,
    [REC_EFF_DT]        DATE          NULL,
    [REC_EXP_DT]        DATE          NULL,
    [EDI_TRANSFER_STAT] CHAR (1)      NULL,
    [CURRENT_TIMESTAMP] DATETIME      NULL,
    [CMPNY_ID]          INT           NULL,
    [UPD_ADDR_1]        VARCHAR (200) NULL,
    [UPD_ADDR_2]        VARCHAR (100) NULL
);

