CREATE TABLE [STAGE].[PRC_AUTH_TEST17] (
    [COACCTID]        VARCHAR (20)  NULL,
    [COACCTSHIPNAME]  VARCHAR (100) NULL,
    [COACCTSHIPADDR1] VARCHAR (100) NULL,
    [COACCTSHIPCITY]  VARCHAR (100) NULL,
    [COACCTSHIPSTATE] VARCHAR (2)   NULL,
    [COACCTSHIPZIP]   VARCHAR (10)  NULL,
    [SALES_AMT_PRIOR] INT           NULL,
    [SALES_AMT_CURR]  INT           NULL,
    [NTWRK_AMT_PRIOR] INT           NULL,
    [NTWRK_AMT_CURR]  INT           NULL
);

