CREATE TABLE [STAGE].[PRC_AUTH] (
    [PRC_AUTH_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [GPO_NM]            VARCHAR (15)  NULL,
    [GPO_MBR_ID]        VARCHAR (15)  NULL,
    [GPO_MBR_NM]        VARCHAR (250) NULL,
    [GPO_MBR_ADDR1]     VARCHAR (250) NULL,
    [GPO_MBR_ADDR2]     VARCHAR (250) NULL,
    [GPO_MBR_CITY]      VARCHAR (50)  NULL,
    [GPO_MBR_ST]        VARCHAR (50)  NULL,
    [GPO_MBR_ZIP]       VARCHAR (5)   NULL,
    [GPO_CNT_NR]        VARCHAR (15)  NULL,
    [MFG_CNT_NR]        VARCHAR (15)  NULL,
    [TIER_NR]           INT           NULL,
    [TIER_DESC]         VARCHAR (250) NULL,
    [PRC_EFF_DT]        DATE          NULL,
    [PRC_EXP_DT]        DATE          NULL,
    [IDN_NM]            VARCHAR (250) NULL,
    [DIST_NM_1]         VARCHAR (250) NULL,
    [DIST_NM_2]         VARCHAR (250) NULL,
    [PRC_ACT_NR]        VARCHAR (50)  NULL,
    [LIC_NR]            VARCHAR (10)  NULL,
    [PRC_ACT_DT]        DATE          NULL,
    [STATUS]            VARCHAR (20)  NULL,
    [SRC_REC_ID]        VARCHAR (15)  NULL,
    [DEA]               VARCHAR (50)  NULL,
    [GLN]               VARCHAR (50)  NULL,
    [HIN]               VARCHAR (50)  NULL,
    [SEGMENT]           VARCHAR (50)  NULL,
    [REC_STAT]          CHAR (1)      DEFAULT ('A') NULL,
    [REC_EFF_DT]        AS            ([PRC_EFF_DT]),
    [REC_EXP_DT]        AS            ([PRC_EXP_DT]),
    [CURRENT_TIMESTAMP] DATETIME      NULL,
    [PRC_STAT_CD]       CHAR (1)      DEFAULT ('P') NULL,
    [PRCS_IN]           CHAR (1)      CONSTRAINT [D_PRC_AUTH_PRCS_IN] DEFAULT ('P') NOT NULL
);



