CREATE TABLE [STAGE].[RELATIONSHIP] (
    [COMPANYID]        FLOAT (53)    NULL,
    [PARENTCOMPANYID]  FLOAT (53)    NULL,
    [RELATIONSHIPTYPE] VARCHAR (MAX) NULL,
    [PARENTIDNCOUNT]   FLOAT (53)    NULL,
    [DISTANCETOCHILD]  FLOAT (53)    NULL
);

