CREATE TABLE [STAGE].[TEMP_LAUNDRY_STG1] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [SRCE_DATA_ID]  INT           NOT NULL,
    [UPD_NM]        VARCHAR (255) NULL,
    [UPD_ADDR1]     VARCHAR (250) NULL,
    [UPD_ADDR2]     VARCHAR (250) NULL,
    [ST_NR_1]       VARCHAR (100) NULL,
    [ST_NM_1]       VARCHAR (100) NULL,
    [ST_TYP_1]      VARCHAR (50)  NULL,
    [ADRR2_TYP]     VARCHAR (40)  NULL,
    [ADRR2_NR]      VARCHAR (20)  NULL,
    [ADDR1_STAT_CD] TINYINT       NULL,
    [ADDR2_STAT_CD] TINYINT       NULL,
    [ST_NR_2]       VARCHAR (250) NULL,
    [ST_NM_2]       VARCHAR (250) NULL,
    [ST_TYP_2]      VARCHAR (250) NULL,
    [ADDR_2_CNDT]   VARCHAR (250) NULL,
    [ADDR_SRCE]     SMALLINT      NULL,
    [COMPANY_ID]    INT           NULL,
    [ADDR_SRC_CNFD] SMALLINT      NULL,
    [ST_1]          VARCHAR (250) NULL,
    [ST_2]          VARCHAR (250) NULL,
    [ADDR1]         VARCHAR (255) NULL,
    [ADDR2]         VARCHAR (255) NULL,
    [SUFFIX]        VARCHAR (255) NULL,
    [CITY]          VARCHAR (100) NULL,
    [STATE]         CHAR (2)      NULL,
    [ZIP]           VARCHAR (10)  NULL,
    [SUFFIX_VLD_IN] CHAR (1)      NULL,
    [ORIG_NM]       VARCHAR (255) NULL,
    [MTCH_NM]       VARCHAR (255) NULL,
    [ALT_NM]        VARCHAR (150) NULL,
    [NM_STAT_CD]    TINYINT       NULL,
    [ALT_ADDR1]     VARCHAR (100) NULL,
    [ADDR3]         VARCHAR (50)  NULL,
    [DIRECTION]     NVARCHAR (10) NULL,
    [WILD_COL]      VARCHAR (255) NULL,
    [ADRR3_TYP]     VARCHAR (40)  NULL,
    [ADRR3_NR]      VARCHAR (20)  NULL
);

