CREATE TABLE [STAGE].[TEMP_GRP_SPR] (
    [GRP_NM] VARCHAR (100) NULL,
    [ADDR_1] VARCHAR (250) NULL,
    [CITY]   VARCHAR (100) NULL,
    [STATE]  VARCHAR (20)  NULL,
    [ZIP]    VARCHAR (10)  NULL
);

