CREATE TABLE [STAGE].[TRC_PROD_CORR_XREF] (
    [DIST_NR]     VARCHAR (20)   NULL,
    [DIST_ID]     NVARCHAR (255) NULL,
    [TRC_PROD_ID] NVARCHAR (255) NULL,
    [UPD_PROD_ID] NVARCHAR (255) NULL
);

