CREATE TABLE [STAGE].[TRC_ENDUSER_3K] (
    [TRC_ENDUSER_1_ID]  INT             IDENTITY (1, 1) NOT NULL,
    [DISTCOID]          VARCHAR (20)    NULL,
    [DISTID]            VARCHAR (8)     NULL,
    [DISTACCTID]        VARCHAR (20)    NULL,
    [DISTACCTSHIPNAME]  VARCHAR (255)   NULL,
    [DISTACCTSHIPADDR1] VARCHAR (50)    NULL,
    [DISTACCTSHIPADDR2] VARCHAR (50)    NULL,
    [DISTACCTSHIPCITY]  VARCHAR (50)    NULL,
    [DISTACCTSHIPSTATE] VARCHAR (2)     NULL,
    [DISTACCTSHIPZIP]   VARCHAR (10)    NULL,
    [COACCTID]          VARCHAR (20)    NULL,
    [COACCTMAX]         VARCHAR (20)    NULL,
    [SALES_SUM]         NUMERIC (38, 2) NULL,
    [ISSUE]             VARCHAR (40)    NULL,
    [UPD_ADDR1]         VARCHAR (250)   NULL,
    [UPD_ADDR2]         VARCHAR (250)   NULL,
    [ST_NR]             SMALLINT        NULL,
    [ST_NM]             VARCHAR (100)   NULL,
    [ST_TYP]            VARCHAR (50)    NULL,
    [ADRR2_TYP]         VARCHAR (40)    NULL,
    [ADRR2_NR]          VARCHAR (20)    NULL,
    [Cleanse_Flag]      CHAR (1)        NULL,
    [Match_by_Addr]     SMALLINT        NULL,
    [Match_by_MAX]      SMALLINT        NULL,
    [Match_by_DQS_NM]   SMALLINT        NULL,
    [Match_by_DQS_Addr] SMALLINT        NULL,
    [COMPANY_ID_MAX]    INT             NULL,
    [COMPANY_ID]        INT             NULL,
    [UPD_NAME]          VARCHAR (255)   NULL,
    [PROPER_NM]         VARCHAR (200)   NULL
);

