CREATE TABLE [STAGE].[TRC_CNT_CORR_XREF] (
    [PROD_ID]        VARCHAR (20)   NULL,
    [TRC_CNT_ID]     NVARCHAR (255) NULL,
    [UPD_CNT_ID]     NVARCHAR (255) NULL,
    [UPD_CNT_EXP_DT] DATE           NULL,
    [TRC_CNT_TYP]    CHAR (3)       NULL
);

