CREATE TABLE [SNDBX].[TEST_DUP] (
    [DISTID]            VARCHAR (8)  NULL,
    [DISTACCTID]        VARCHAR (20) NULL,
    [DISTACCTSHIPNAME]  VARCHAR (50) NULL,
    [DISTACCTSHIPADDR1] VARCHAR (50) NULL,
    [DISTACCTSHIPADDR2] VARCHAR (50) NULL,
    [DISTACCTSHIPCITY]  VARCHAR (50) NULL,
    [DISTACCTSHIPSTATE] VARCHAR (2)  NULL,
    [DISTACCTSHIPZIP]   VARCHAR (10) NULL
);

