CREATE TABLE [VT_TEST].[DDS_CO_DIST_XREF] (
    [COACCTID]        VARCHAR (20)    NULL,
    [DISTACCTID]      VARCHAR (20)    NULL,
    [DISTACCTSHIPZIP] VARCHAR (10)    NULL,
    [SLS_AMT]         NUMERIC (38, 2) NULL
);

