CREATE TABLE [VT_TEST].[VT_SAF] (
    [COACCTID]        VARCHAR (20)    NULL,
    [COACCTSHIPNAME]  VARCHAR (100)   NULL,
    [COACCTSHIPADDR1] VARCHAR (100)   NULL,
    [COACCTSHIPADDR2] VARCHAR (50)    NULL,
    [COACCTSHIPCITY]  VARCHAR (100)   NULL,
    [COACCTSHIPSTATE] VARCHAR (2)     NULL,
    [COACCTSHIPZIP]   VARCHAR (10)    NULL,
    [SLS_AMT]         NUMERIC (38, 2) NULL,
    [DISTACCT_COUNT]  INT             NULL
);

