CREATE PROCEDURE [STAGE].[spCORTHALL_LAUNDRY] 
@ID INT = NULL
WITH EXEC AS CALLER
AS
BEGIN  

--------------- CLEANSE NAME -----------------------------------
UPDATE STAGE.CROTHALL_COMPANY
SET ORIG_CMPNY_NM = CMPNY_NM;

UPDATE STAGE.CROTHALL_COMPANY
SET CROTHALL_CMPNY_ID = convert(int,STAGE.fnFirstWord( CMPNY_NM)),
    CMPNY_NM = LTRIM(STAGE.fnSecondPart(CMPNY_NM, LEN(STAGE.fnFirstWord( CMPNY_NM))+1 ))
WHERE ISNUMERIC(STAGE.fnFirstWord( CMPNY_NM)) = 1;

    UPDATE STAGE.CROTHALL_COMPANY
    SET  
      CMPNY_NM = LEFT(CMPNY_NM,CHARINDEX('{',CMPNY_NM)-2),
      ADDR_2 = SUBSTRING(CMPNY_NM,CHARINDEX('{', CMPNY_NM),LEN(CMPNY_NM)-CHARINDEX('{', CMPNY_NM)+1)
    WHERE CHARINDEX('{',CMPNY_NM)>0;
  
    UPDATE STAGE.CROTHALL_COMPANY
    SET  
      CMPNY_NM = LEFT(CMPNY_NM,CHARINDEX('(',CMPNY_NM)-2),
      ADDR_2 = SUBSTRING(CMPNY_NM,CHARINDEX('(', CMPNY_NM),LEN(CMPNY_NM)-CHARINDEX('(', CMPNY_NM)+1)
    WHERE CHARINDEX('(',CMPNY_NM)>0;
    
    UPDATE STAGE.CROTHALL_COMPANY
    SET  
      CMPNY_NM = LTRIM(RTRIM(LEFT(CMPNY_NM, LEN(CMPNY_NM)-LEN('- CLOSING')))),
      ADDR_2 = 'CLOSING'
    WHERE CHARINDEX('- CLOSING',CMPNY_NM)>0;
    
    UPDATE STAGE.CROTHALL_COMPANY
    SET  
      CMPNY_NM = LTRIM(RTRIM(LEFT(CMPNY_NM, LEN(CMPNY_NM)-LEN('-CLOSING')))),
      ADDR_2 = 'CLOSING'
    WHERE CHARINDEX('-CLOSING',CMPNY_NM)>0;
    
  UPDATE STAGE.CROTHALL_COMPANY
    SET CMPNY_NM   = STAGE.fnGet_FirstPart ( CMPNY_NM, CHARINDEX('CLOSING', CMPNY_NM) -2) 
  WHERE CHARINDEX('CLOSING', CMPNY_NM)>0;
  
    UPDATE STAGE.CROTHALL_COMPANY
    SET CMPNY_NM   = LTRIM(RTRIM(STAGE.fnRemoveSpace(REPLACE(CMPNY_NM,'-',''))));
  
  UPDATE STAGE.CROTHALL_COMPANY
    SET CROTHALL_CMPNY_ID = 'CROTHALL'
  WHERE ADDR_2 LIKE '%CROTHALL%'
  AND CROTHALL_CMPNY_ID IS NULL;
  
  UPDATE STAGE.CROTHALL_COMPANY
    SET ADDR_2 = NULL;
  
  -------------------- CLEANSE ADDRESS -----------------------------------------------------------
  
  TRUNCATE TABLE STAGE.TEMP_ADDR_LAUNDRY;
  
  INSERT INTO STAGE.TEMP_ADDR_LAUNDRY( SRCE_DATA_ID, ORIG_NM, ADDR1, ADDR2, CITY, STATE, ZIP )
  SELECT PDI_CROTHALL_CMPNY_ID, CMPNY_NM,  ADDR_1, ADDR_2, CITY, ST, ZIP 
  FROM STAGE.CROTHALL_COMPANY;

  EXEC [STAGE].[spADDR_LAUNDRY_V2] ;

  UPDATE T
    SET T.UPD_ADDR1 = UPPER(S.UPD_ADDR1),
     T.UPD_ADDR2 = UPPER(S.UPD_ADDR2),
     T.UPD_CITY = UPPER(S.CITY)
  FROM STAGE.CROTHALL_COMPANY  T
  JOIN STAGE.TEMP_ADDR_LAUNDRY S ON T.PDI_CROTHALL_CMPNY_ID = S.SRCE_DATA_ID;
  
  -------------------------------------------------------------------------------------
  
  UPDATE CR
  SET CR.CMPNY_ID = CM.CMPNY_ID
  FROM STAGE.CROTHALL_COMPANY CR
  JOIN CMPNY.COMPANY CM ON CR.UPD_ADDR1 = CM.CMPNY_ADDR_1 AND CR.ZIP = CM.CMPNY_ZIP
  WHERE CM.CMPNY_ADDR_2 IS NULL

  UPDATE CR
  SET CR.CMPNY_ID = CM.CMPNY_ID
  FROM STAGE.CROTHALL_COMPANY CR
  JOIN CMPNY.COMPANY CM ON CR.UPD_ADDR1 = CM.CMPNY_ADDR_1 AND CR.UPD_ADDR2 = CM.CMPNY_ADDR_2 AND CR.ZIP = CM.CMPNY_ZIP
  WHERE CM.CMPNY_ADDR_2 IS NOT NULL AND CR.UPD_ADDR2 IS NOT NULL
  AND CR.CMPNY_ID  IS NULL
  
  
    END;