CREATE PROCEDURE [STAGE].[spDHC_TL] 
@ID INT = NULL
WITH EXEC AS CALLER
AS
BEGIN  

  -------------------- CLEANSE NAME -----------------------------------

  EXEC [STAGE].[spDHC_NAME_CLEANSE];
  
  -------------------- CLEANSE ADDRESS --------------------------------
  
  TRUNCATE TABLE STAGE.TEMP_ADDR_LAUNDRY;
  
  INSERT INTO STAGE.TEMP_ADDR_LAUNDRY( SRCE_DATA_ID, ADDR1, ADDR2, CITY, STATE, ZIP )
  SELECT DHC_CO_ID, DHC_CO_ADDR_1, DHC_CO_ADDR_2, DHC_CO_CITY, DHC_CO_ST, DHC_CO_ZIP
  FROM STAGE.DHC_COMPANY ;

  EXEC [STAGE].[spNAD_LAUNDRY_LITE];

  UPDATE D
    SET 
     UPD_ADDR1 = UPPER(T.UPD_ADDR1),
     UPD_ADDR2 = UPPER(T.UPD_ADDR2),
     UPDT_CO_CITY = UPPER(T.CITY),
     UNIQ_FLAG = CASE WHEN T.ADRR2_TYP IS NULL THEN 1 ELSE 2 END 
  FROM STAGE.DHC_COMPANY D
  JOIN STAGE.TEMP_ADDR_LAUNDRY T ON D.DHC_CO_ID = T.SRCE_DATA_ID
  OPTION (MERGE JOIN) ;
  
  -------------------------------------------------------------------------------------
  -- Unique Flag for DHC

  UPDATE D1
    SET UNIQ_FLAG = 11
  FROM STAGE.DHC_COMPANY D1 
  JOIN  (SELECT C.UPD_ADDR1, C.DHC_CO_ZIP, count(*) CNT
    FROM STAGE.DHC_COMPANY C
    WHERE C.UNIQ_FLAG = 1
    GROUP BY C.UPD_ADDR1, C.DHC_CO_ZIP
    HAVING count(*)  > 1 ) D2
  ON  D1.UPD_ADDR1 = D2.UPD_ADDR1 AND D1.DHC_CO_ZIP = D2.DHC_CO_ZIP
  WHERE D1.UNIQ_FLAG = 1 
  
  UPDATE D1
    SET UNIQ_FLAG = 12
  FROM STAGE.DHC_COMPANY D1 
  JOIN  (SELECT C.UPD_ADDR1, C.UPD_ADDR2 , C.DHC_CO_ZIP, count(*) CNT
    FROM STAGE.DHC_COMPANY C
    WHERE C.UNIQ_FLAG = 2
    GROUP BY C.UPD_ADDR1, C.UPD_ADDR2, C.DHC_CO_ZIP
    HAVING count(*)  > 1 ) D2
  ON  D1.UPD_ADDR1 = D2.UPD_ADDR1 AND D1.UPD_ADDR2 = D2.UPD_ADDR2 AND D1.DHC_CO_ZIP = D2.DHC_CO_ZIP
  WHERE D1.UNIQ_FLAG = 2

  EXEC STAGE.spLOAD_DHC_TO_COMPANY;
  
  TRUNCATE TABLE STAGE.TEMP_ADDR_LAUNDRY;
  
    END;