CREATE PROCEDURE [STAGE].[spGet_similar_company]
@vCMPNY varchar(196), @vZIP varchar(10)
WITH EXEC AS CALLER
AS
BEGIN

  SELECT DISTINCT CMPNY_NM, @vCMPNY ,@vZIP, Z.State,  
  CMPNY_ADDR_1, CMPNY_CITY, CMPNY_ST, CMPNY_ZIP, S.CMPNY_SGMNT_NM,
  STAGE.fnLEVENSHTEIN(@vCMPNY,CMPNY_NM) AS [NM_PROXIMITY], LEN(@vCMPNY) WRD_LN, CONVERT(DECIMAL(10,2),STAGE.fnGet_Distance(@vZIP,CMPNY_ZIP)/3/1760) DISTNACE
  FROM CMPNY.COMPANY C
  JOIN CMPNY.COMPANY_SEGMENT S ON C.CMPNY_SGMNT_ID = S.CMPNY_SGMNT_ID
  JOIN STG0.ZIP_CODE Z ON LEFT(Z.Zipcode,5) = @vZIP 
  WHERE CMPNY_NM LIKE '%'+@vCMPNY+'%'
  --AND STAGE.fnGet_Distance('30062',CMPNY_ZIP) = 0
  ORDER BY 12, 11

END