CREATE PROCEDURE [STAGE].[spGPO_MMBR_LAUNDRY]
WITH EXEC AS CALLER
AS
BEGIN  

--- Fix the GPO name first

 UPDATE STAGE.GPO_MEMBER
 SET GPO_NM = 'The Resource Group'
 WHERE GPO_NM = 'Ascensioin';

 UPDATE G
 SET GPO_CMPNY_ID = C.CMPNY_ID
 FROM STAGE.GPO_MEMBER G 
 JOIN  CMPNY.COMPANY C ON G.GPO_NM = C.CMPNY_NM
 WHERE CMPNY_SGMNT_ID = 8
 AND GPO_CMPNY_ID IS NULL;

--- ADDRESS CLEAN --
    TRUNCATE TABLE MDM_STAGE.TEMP_ADDR;
    
  INSERT INTO MDM_STAGE.TEMP_ADDR ( SRC_ID, ADDR_1, ADDR_2)
  SELECT DISTINCT PDI_GPO_MMBR_ID, MMBR_ADDR_1, MMBR_ADDR_2
  FROM STAGE.GPO_MEMBER ;
  
  EXEC [STAGE].[spADDR_LAUNDRY];
  
  TRUNCATE TABLE MDM_STAGE.GPO_MMBR_ADDR_PARTS;
  
  INSERT INTO MDM_STAGE.GPO_MMBR_ADDR_PARTS ( 
    SRC_ID, ST_NR, ST_NM, ST_TYP, ST_DIR, ST_NR_2, BLDG_NR, FL_NR, STE_NR, DIR_1, ADDR_1, ADDR_2  )
  SELECT 
    SRC_ID, ST_NR, ST_NM, ST_TYP, ST_DIR, ST_NR_2, BLDG_NR, FL_NR, STE_NR, DIR_1, ADDR_1, ADDR_2  
  FROM MDM_STAGE.TEMP_ADDR_PARTS
  ;  
  
  
  UPDATE C
    SET G.UPD_ADDR1 = A.ADDR_1, G.UPD_ADDR2 =  A.ADDR_2
  FROM STAGE.GPO_MEMBER G
  JOIN MDM_STAGE.TEMP_ADDR_PARTS A ON G.PDI_GPO_MMBR_ID = A.SRC_ID;
  
  TRUNCATE TABLE  MDM_STAGE.TEMP_ADDR_PARTS;
  TRUNCATE TABLE  MDM_STAGE.TEMP_ADDR;
  
  UPDATE C SET
    G.CMPNY_CITY = Z.City
  from STAGE.GPO_MEMBER G
  JOIN REF.ZIP_CODE Z ON G.MMBR_ZIP = Z.Zipcode
  WHERE  Z.LocationType = 'PRIMARY'
  AND Z.City <> G.MMBR_CITY ;
  
  END;