CREATE PROCEDURE [STAGE].[spLOAD_EDI_DATA]
@vDist_NM varchar(20), @vYYYYMM char(6)
WITH EXEC AS CALLER
AS
BEGIN
 BEGIN
   MERGE [STAGE].[SLS_TRC_LOAD_DTL] T
    USING (
      SELECT  DI.DIST_ID AS DIST_ID,
      HDRCUS AS DIST_TRC_NM,
     convert(int,replace(CONVERT(DATE, left(H.[current timestamp],10)),'-','')) AS RECVD_DTE,
      --LEFT(H.[current timestamp],4)+'-'+SUBSTRING(H.[current timestamp],6,2)+'-'+SUBSTRING(H.[current timestamp],9,2) AS RECVD_DTE_DISPLY,
      'PENDING' AS LOAD_STAT, 'EDI' AS SRC_FILE_TYP,
      MAX(CAST((S.INVDTE/100) as INTEGER)) AS SALES_PERIOD, COUNT(S.SDDSEQ) AS REC_CNT 
      FROM  
      FTPOUT.E867HDR_DAILY_HIST H
      JOIN FTPOUT.E867DTL_DAILY_HIST D ON H.HDRSEQ = D.DTLSEQ AND H.HDRCUS = D.DTLCUS
      JOIN FTPOUT.E867SDTL_DAILY_HIST S ON D.DDLSEQ = S.SDLSEQ AND D.DTLCUS = S.SDTCUS
      JOIN STAGE.DIM_DISTRIBUTOR DI ON H.HDRCUS = DI.TRACING_NAME
      WHERE  
      LEFT(H.[current timestamp],4)  = LEFT(@vYYYYMM,4)
      AND SUBSTRING(H.[current timestamp],6,2) = RIGHT(@vYYYYMM,2)
      AND HDRCUS = isnull(@vDIst_NM,HDRCUS)
      AND HDRCUS NOT IN ('GHX HCA') --  NOT IN ('CARDINAL', 'OWENS','SENECA') 
      GROUP BY 
      DI.DIST_ID, H.HDRCUS,
      convert(int,replace(CONVERT(DATE, left(H.[current timestamp],10)),'-','')) 
      ) S ON T.DIST_ID = S.DIST_ID AND T.RECVD_DTE = S.RECVD_DTE
      
    WHEN MATCHED THEN UPDATE SET LOAD_STAT = 'PENDING' 
      
    WHEN NOT MATCHED BY TARGET THEN   -- That means it is a new Contract

      INSERT 
      ( DIST_ID, DIST_TRC_NM, SALES_PERIOD, RECVD_DTE, LOAD_STAT,SRC_FILE_TYP, REC_CNT)
      VALUES
      ( DIST_ID, DIST_TRC_NM, SALES_PERIOD, RECVD_DTE, LOAD_STAT,SRC_FILE_TYP, REC_CNT);
  
    END
   


   UPDATE  [STAGE].[SLS_TRC_LOAD_DTL]
   SET SALES_PERIOD =case when len(SALES_PERIOD)=6 then SALES_PERIOD*100+1
   else SALES_PERIOD end;

  DELETE C FROM [STAGE].[SALES_TRACING_CURR] C
  INNER JOIN [STAGE].[SLS_TRC_LOAD_DTL] L 
    ON C.DIST_NR = L.DIST_ID 
    AND C.LOAD_ID = L.LOAD_ID
    AND L.LOAD_STAT = 'PENDING' AND L.SRC_FILE_TYP = 'EDI' ;
  
  INSERT INTO [STAGE].[SALES_TRACING_CURR]
    ([YEAR], [MNTH],[DAY],[SALES_PERIOD], [DIST_NR], [DIST_ID], [RPT_DT], [INV_ID],
    [INV_DT], 
    [INV_DT_NR], [TRC_TRNS_TYP], 
    [TRC_CNT_ID], [TRC_PROD_ID], [TRC_QTY_SLD], [TRC_UNIT], [CTPRC], [DIPRC], [CAPRC],
    [TRC_RBT_AMT], EDISDTLSEQ, [SHPTO_ID], EDIDTLSEQ, [SRC_FILE_TYP],SLS_CALC_STAT, RBT_CALC_STAT, [CURRENT TIMESTAMP], [LOAD_ID] )
    SELECT
    LEFT(H.[current timestamp],4), SUBSTRING(H.[current timestamp],6,2),SUBSTRING(H.[current timestamp],9,2),
    C.SALES_PERIOD , C.DIST_ID AS [DIST_NR], H.HDRCUS AS [DIST_ID], H.RPTDTE as [RPT_DT], S.DIDESC AS [INV_ID], 
    CONVERT(DATE,LEFT(S.INVDTE,4)+'-'+LEFT(RIGHT(S.INVDTE,4),2)+'-'+RIGHT(S.INVDTE,2)),
    S.INVDTE AS [INV_DT_NR], 
    D.PTDTYP as [TRC_TRNS_TYP], 
    S.BCDESC AS [TRC_CNT_ID], S.SELNUM AS [TRC_Prod_ID], S.QTYSLD AS [TRC_QTY_SLD], S.QTYSUM AS [TRC UNIT], 
    S.CTPRC, S.DIPRC, S.CAPRC, [AMTCT$] AS [Rebate Amount], S.SLLSEQ, D.STCODE, S.SDLSEQ, 'EDI','P','P', CURRENT_TIMESTAMP, C.LOAD_ID
    FROM PDI_SALESTRACING_dev.FTPOUT.E867HDR_DAILY_HIST H 
    JOIN PDI_SALESTRACING_dev.FTPOUT.E867DTL_DAILY_HIST D ON H.HDRCUS = D.DTLCUS AND H.HDRSEQ = D.DTLSEQ
    JOIN PDI_SALESTRACING_dev.FTPOUT.E867SDTL_DAILY_HIST S ON D.DTLCUS = S.SDTCUS AND D.DDLSEQ = S.SDLSEQ
    JOIN [STAGE].[SLS_TRC_LOAD_DTL] C 
      ON H.HDRCUS = C.DIST_TRC_NM 
      AND convert(int,replace(CONVERT(DATE, left(H.[current timestamp],10)),'-','')) = C.RECVD_DTE
      AND C.LOAD_STAT = 'PENDING'
    WHERE D.[PTDTYP] NOT IN ('IB') ;

      UPDATE [STAGE].[SLS_TRC_LOAD_DTL]
      SET LOAD_STAT = 'COMPLETE'
      WHERE LOAD_STAT = 'PENDING';
END