CREATE PROCEDURE [STAGE].[spLOAD_DHC_TO_COMPANY] 
WITH EXEC AS CALLER
AS
BEGIN

  ---------------------------------------  
  --- Load Company Master Data from DHC
  ---------------------------------------
  
    TRUNCATE TABLE CMPNY.COMPANY;
  
    -- FIRST LOAD THE UNQIUE ADDRESS DATA WHICH DOES NOT HAVE DUPLICATES
    INSERT INTO CMPNY.COMPANY
      ( SRC_CMPNY_ID, CMPNY_NM, CMPNY_ALT_NM, ALT_NM_TYP, CMPNY_ADDR_1, CMPNY_ADDR_2, CMPNY_CITY, 
      CMPNY_ST, CMPNY_ZIP, CMPNY_CNTRY, 
      CMPNY_TYP_ID, CMPNY_CTGRY_ID, CMPNY_SGMNT_ID, CMPNY_SUB_SGMNT_ID, 
      COMPANY_URL, NPI_NR, GLN_NR, HIN_NR, DEA_NR, 
      REC_EFF_DT, REC_EXP_DT, REC_STAT_IN, SRC_ID, CMPNY_PRNT_SRC_ID, IDN_SRC_ID, IDN_PRNT_SRC_ID   )
    SELECT 
      DHC_CO_ID, DHC_CO_NM_1, DHC_CO_NM_2, DHC_CO_NM_2_TYP, DHC_CO_ADDR_1, DHC_CO_ADDR_2, UPDT_CO_CITY, 
      DHC_CO_ST, DHC_CO_ZIP, DHC_CO_CNTRY, 
      T.CMPNY_TYP_ID,
      1 AS CMPNY_CTGRY_ID, -- Primary Account
      S.CMPNY_SGMNT_ID , 
      SS.CMPNY_SUB_SGMNT_ID , 
      DHC_CO_WEBSITE, NPI_NR, GLN_NR, HIN_NR, DEA_NR, 
      CONVERT(DATE,GETDATE()) AS REC_EFF_DT, CONVERT(DATE,'9999-12-31') AS REC_EXP_DT, 'A', 
      DS.CMPNY_SRCE_ID, C.HSPTL_PARENT_ID, C.DHC_NTWRK_ID, C.DHC_NTWRK_PARENT_ID
    FROM STAGE.DHC_COMPANY C
      LEFT JOIN CMPNY.COMPANY_TYPE T ON T.CMPNY_TYP_NM = 'EU'
      LEFT JOIN CMPNY.COMPANY_SEGMENT S ON C.DHC_CO_CAT_CD = S.CMPNY_SGMNT_NM
      LEFT JOIN CMPNY.COMPANY_SUB_SEGMENT SS ON S.CMPNY_SGMNT_ID = SS.CMPNY_SGMNT_ID AND C.DHC_CO_SUB_CAT = SS.CMPNY_SUB_SGMNT_NM
      LEFT JOIN CMPNY.COMPANY_DATA_SOURCE DS ON DS.CMPNY_SRCE_NM = 'DHC'
      WHERE C.UNIQ_FLAG IN (1,2)

  ---------------------------------------
  --Pick one record only from duplicates
  ---------------------------------------
  
  -- LOAD BY PRIORITY OF COMPANY TYPE - IF THERE IS MORE THAN ONE
  
  INSERT INTO CMPNY.COMPANY
  ( SRC_CMPNY_ID, CMPNY_NM, CMPNY_ALT_NM, ALT_NM_TYP, CMPNY_ADDR_1, CMPNY_ADDR_2, CMPNY_CITY, 
  CMPNY_ST, CMPNY_ZIP, CMPNY_CNTRY, 
  CMPNY_TYP_ID, CMPNY_CTGRY_ID, CMPNY_SGMNT_ID, CMPNY_SUB_SGMNT_ID, 
  COMPANY_URL, NPI_NR, GLN_NR, HIN_NR, DEA_NR, 
  REC_EFF_DT, REC_EXP_DT, REC_STAT_IN, SRC_ID,
  CMPNY_PRNT_SRC_ID, IDN_SRC_ID, IDN_PRNT_SRC_ID)
  SELECT C.DHC_CO_ID, C.DHC_CO_NM_1, C.DHC_CO_NM_2, C.DHC_CO_NM_2_TYP, C.DHC_CO_ADDR_1, C.DHC_CO_ADDR_2, C.UPDT_CO_CITY, 
  C.DHC_CO_ST, C.DHC_CO_ZIP, C.DHC_CO_CNTRY, 
  T.CMPNY_TYP_ID,
  99 AS CMPNY_CTGRY_ID,  -- MULTIPLE - have those in the name table for matching purpose
  --1 AS CMPNY_CTGRY_ID, -- Primary Account
  S.CMPNY_SGMNT_ID , 
  SS.CMPNY_SUB_SGMNT_ID , 
  DHC_CO_WEBSITE, NPI_NR, GLN_NR, HIN_NR, DEA_NR, 
  CONVERT(DATE,GETDATE()) AS REC_EFF_DT, CONVERT(DATE,'9999-12-31') AS REC_EXP_DT, 'A', 
  DS.CMPNY_SRCE_ID, C.HSPTL_PARENT_ID, C.DHC_NTWRK_ID, C.DHC_NTWRK_PARENT_ID
  FROM STAGE.DHC_COMPANY C
  JOIN
    ( SELECT MAX(C.DHC_CO_ID) AS DHC_CO_ID 
      FROM STAGE.DHC_COMPANY C 
      JOIN 
        ( SELECT MAX(C.MFP_FLAG) AS MFP_FLAG, C.UPD_ADDR1, C.DHC_CO_ZIP 
          FROM STAGE.DHC_COMPANY C 
          WHERE C.UNIQ_FLAG = 11
          --and C.DHC_CO_ADDR_1 = '709 Walnut St' 
          GROUP BY C.UPD_ADDR1, C.DHC_CO_ZIP ) 
      I ON C.MFP_FLAG = I.MFP_FLAG AND C.UPD_ADDR1 = I.UPD_ADDR1 AND C.DHC_CO_ZIP= I.DHC_CO_ZIP
      GROUP BY I.MFP_FLAG, I.UPD_ADDR1,  I.DHC_CO_ZIP
      ) I1 ON C.DHC_CO_ID = I1.DHC_CO_ID
  LEFT JOIN CMPNY.COMPANY_TYPE T ON T.CMPNY_TYP_NM = 'EU'
  LEFT JOIN CMPNY.COMPANY_SEGMENT S ON C.DHC_CO_CAT_CD = S.CMPNY_SGMNT_NM
  LEFT JOIN CMPNY.COMPANY_SUB_SEGMENT SS ON S.CMPNY_SGMNT_ID = SS.CMPNY_SGMNT_ID AND C.DHC_CO_SUB_CAT = SS.CMPNY_SUB_SGMNT_NM
  LEFT JOIN CMPNY.COMPANY_DATA_SOURCE DS ON DS.CMPNY_SRCE_NM = 'DHC'
  WHERE C.UNIQ_FLAG =11;
  
  INSERT INTO CMPNY.COMPANY
  ( SRC_CMPNY_ID, CMPNY_NM, CMPNY_ALT_NM, ALT_NM_TYP, CMPNY_ADDR_1, CMPNY_ADDR_2, CMPNY_CITY, 
  CMPNY_ST, CMPNY_ZIP, CMPNY_CNTRY, 
  CMPNY_TYP_ID, CMPNY_CTGRY_ID, CMPNY_SGMNT_ID, CMPNY_SUB_SGMNT_ID, 
  COMPANY_URL, NPI_NR, GLN_NR, HIN_NR, DEA_NR, 
  REC_EFF_DT, REC_EXP_DT, REC_STAT_IN, SRC_ID,
  CMPNY_PRNT_SRC_ID, IDN_SRC_ID, IDN_PRNT_SRC_ID)
  SELECT C.DHC_CO_ID, C.DHC_CO_NM_1, C.DHC_CO_NM_2, C.DHC_CO_NM_2_TYP, C.DHC_CO_ADDR_1, C.DHC_CO_ADDR_2, C.UPDT_CO_CITY, 
  C.DHC_CO_ST, C.DHC_CO_ZIP, C.DHC_CO_CNTRY, 
  T.CMPNY_TYP_ID,
  99 AS CMPNY_CTGRY_ID,  -- MULTIPLE - have those in the name table for matching purpose
  --1 AS CMPNY_CTGRY_ID, -- Primary Account
  S.CMPNY_SGMNT_ID , 
  SS.CMPNY_SUB_SGMNT_ID , 
  DHC_CO_WEBSITE, NPI_NR, GLN_NR, HIN_NR, DEA_NR, 
  CONVERT(DATE,GETDATE()) AS REC_EFF_DT, CONVERT(DATE,'9999-12-31') AS REC_EXP_DT, 'A', 
  DS.CMPNY_SRCE_ID, C.HSPTL_PARENT_ID, C.DHC_NTWRK_ID, C.DHC_NTWRK_PARENT_ID
  FROM STAGE.DHC_COMPANY C
  JOIN
    ( SELECT MAX(C.DHC_CO_ID) AS DHC_CO_ID 
      FROM STAGE.DHC_COMPANY C 
      JOIN 
        ( SELECT MAX(C.MFP_FLAG) AS MFP_FLAG, C.UPD_ADDR1, C.UPD_ADDR2, C.DHC_CO_ZIP 
          FROM STAGE.DHC_COMPANY C 
          WHERE C.UNIQ_FLAG = 12
          --and C.DHC_CO_ADDR_1 = '709 Walnut St' 
          GROUP BY C.UPD_ADDR1, C.UPD_ADDR2, C.DHC_CO_ZIP ) 
      I ON C.MFP_FLAG = I.MFP_FLAG AND C.UPD_ADDR1 = I.UPD_ADDR1 AND C.UPD_ADDR2 = I.UPD_ADDR2 AND C.DHC_CO_ZIP= I.DHC_CO_ZIP
      GROUP BY I.MFP_FLAG, I.UPD_ADDR1, I.UPD_ADDR2, I.DHC_CO_ZIP
      ) I1 ON C.DHC_CO_ID = I1.DHC_CO_ID
  LEFT JOIN CMPNY.COMPANY_TYPE T ON T.CMPNY_TYP_NM = 'EU'
  LEFT JOIN CMPNY.COMPANY_SEGMENT S ON C.DHC_CO_CAT_CD = S.CMPNY_SGMNT_NM
  LEFT JOIN CMPNY.COMPANY_SUB_SEGMENT SS ON S.CMPNY_SGMNT_ID = SS.CMPNY_SGMNT_ID AND C.DHC_CO_SUB_CAT = SS.CMPNY_SUB_SGMNT_NM
  LEFT JOIN CMPNY.COMPANY_DATA_SOURCE DS ON DS.CMPNY_SRCE_NM = 'DHC'
  WHERE C.UNIQ_FLAG =12;
  
  
-- Load address parts for matching process
/*
  TRUNCATE TABLE  STAGE.CMPNY_ADDR_PARTS;

  INSERT INTO STAGE.CMPNY_ADDR_PARTS
  ( CMPNY_COMPANY_ID, SRC_DATA_ID, ST_NR_1, ST_NM_1, ST_TYP_1, DIRECTION, ADRR2_TYP, ADRR2_NR, ADRR3_TYP, ADRR3_NR, CITY, STATE, ZIP)
  SELECT 
    C.CMPNY_ID, T.SRCE_DATA_ID, T.ST_NR_1, T.ST_NM_1, T.ST_TYP_1, T.DIRECTION, T.ADRR2_TYP, T.ADRR2_NR, T.ADRR3_TYP, T.ADRR3_NR, T.CITY, T.STATE, T.ZIP 
  FROM CMPNY.COMPANY C
  JOIN STAGE.TEMP_ADDR_LAUNDRY T ON C.SRC_CMPNY_ID = T.SRCE_DATA_ID;
 */ 
  --UPDATE CMPNY.COMPANY SET CMPNY_PRNT_ID = NULL
  
  UPDATE C SET 
   CMPNY_PRNT_ID = CP.CMPNY_ID
  FROM CMPNY.COMPANY C
  JOIN STAGE.DHC_COMPANY D ON C.SRC_CMPNY_ID = D.DHC_CO_ID
  JOIN CMPNY.COMPANY CP ON D.HSPTL_PARENT_ID = CP.SRC_CMPNY_ID 
  WHERE (D.HSPTL_PARENT_ID IS NOT NULL AND D.HSPTL_PARENT_ID>0);
  
  UPDATE C SET  
    C.IDN_CMPNY_ID = CI.CMPNY_ID
  FROM CMPNY.COMPANY C
  JOIN STAGE.DHC_COMPANY D ON C.SRC_CMPNY_ID = D.DHC_CO_ID
  JOIN CMPNY.COMPANY CI ON D.DHC_NTWRK_ID = CI.SRC_CMPNY_ID 
  WHERE (D.DHC_NTWRK_ID  IS NOT NULL AND D.DHC_NTWRK_ID >0);
  
  UPDATE C SET 
    C.IDN_PRNT_CMPNY_ID = CI.CMPNY_ID
  FROM CMPNY.COMPANY C
  JOIN STAGE.DHC_COMPANY D ON C.SRC_CMPNY_ID = D.DHC_CO_ID
  JOIN CMPNY.COMPANY CI ON D.DHC_NTWRK_PARENT_ID = CI.SRC_CMPNY_ID 
  WHERE (D.DHC_NTWRK_PARENT_ID  IS NOT NULL AND D.DHC_NTWRK_PARENT_ID >0);
  
END