CREATE PROCEDURE [STAGE].[spMatch_MasterData_3k]
WITH EXEC AS CALLER
AS
BEGIN  

  UPDATE STAGE.TRC_ENDUSER_3K
    SET COMPANY_ID = NULL;

SELECT  *, UPD_ADDR1, UPD_ADDR2
FROM STAGE.TRC_ENDUSER_3K

UPDATE E
SET COMPANY_ID = C.CMPNY_ID
FROM STAGE.TRC_ENDUSER_3K E
JOIN CMPNY.COMPANY C ON E.UPD_ADDR1 = C.CMPNY_ADDR_1 AND E.DISTACCTSHIPZIP = C.CMPNY_ZIP
AND C.CMPNY_ADDR_2 IS NULL AND E.UPD_ADDR2 IS NULL

UPDATE E
SET COMPANY_ID = C.CMPNY_ID
FROM STAGE.TRC_ENDUSER_3K E
JOIN CMPNY.COMPANY C ON E.UPD_ADDR1 = C.CMPNY_ADDR_1 AND E.UPD_ADDR2 = C.CMPNY_ADDR_2 AND E.DISTACCTSHIPZIP = C.CMPNY_ZIP
AND C.CMPNY_ADDR_2 IS NOT NULL AND E.UPD_ADDR2 IS NOT NULL



UPDATE E1
  SET E1.COMPANY_ID =E2.COMPANY_ID 
FROM STAGE.TRC_ENDUSER_3K E1
JOIN STAGE.TRC_ENDUSER_3K E2 on E1.DISTCOID = e2.DISTCOID AND E1.DISTACCTID = E2.DISTACCTID AND E1.DISTACCTSHIPZIP = E2.DISTACCTSHIPZIP
AND E1.COMPANY_ID IS NULL AND E2.COMPANY_ID IS NOT NULL
WHERE E2.DISTID in ('CARDINAL','OWNMIN','SCHEIN','SENECA','MOOREM','MEDLINE','HCA','NDC','CROSSTEX','PALMTREE','CARDPRES','TWINMD','MEDDYN','AEROMD','TRINITY')
and E2.UPD_ADDR1 NOT IN ('NO ADRESS','INVALID ADDRESS')

UPDATE STAGE.TRC_ENDUSER_3K
SET Match_by_Addr = 1
WHERE COMPANY_ID IS not null

UPDATE E
SET COMPANY_ID_MAX = X.HOSPITAL_ID
FROM STAGE.TRC_ENDUSER_3K E
JOIN STAGE.PDI_MAX_TO_DEFHC_CROSSWALK X ON E.COACCTMAX = X.CompanyId
JOIN STAGE.DHC_COMPANY C ON X.HOSPITAL_ID = C.DHC_CO_ID

UPDATE STAGE.TRC_ENDUSER_3K
SET COMPANY_ID = COMPANY_ID_MAX, Match_by_MAX = 1
WHERE COMPANY_ID_MAX IS NOT NULL AND COMPANY_ID IS NULL

  END;