CREATE PROCEDURE [STAGE].[spSALES_TRACING_VAR]
@vSales_Period varchar(10)=NULL, @vDist_NR varchar(48) = null
WITH EXEC AS CALLER
AS
BEGIN

--- EMPTY THE TABLE ---
TRUNCATE TABLE TRC.SALES_TRACING_VAR; 

--DROP TABLE TRC.SALES_TRACING_VAR

--- INSERT DATA ---
  INSERT INTO  TRC.SALES_TRACING_VAR
      (  SALES_PERIOD, DIST_NR, DIST_ID, PDI_REC_CNT, VC_REC_CNT, VAR_REC_CNT, PDI_QtySold, VC_QtySold, VAR_QTY_SOLD, PDI_SALESAMT, VC_SALESAMT, VAR_SALES_AMT, SLS_VAR_PCT )    
  SELECT PDI.SALES_PERIOD, PDI.DIST_NR ,  PDI.DIST_ID,
     PDI_REC_CNT, VC_REC_CNT, (PDI_REC_CNT - VC_REC_CNT) VAR_REC_CNT,
     PDI_QtySold,VC_QtySold,
    (PDI_QtySold - VC_QtySold) AS VAR_QTY_SOLD,
    PDI_SALESAMT,VC_SALESAMT,
    (PDI_SALESAMT - VC_SALESAMT) AS VAR_SALES_AMT,
    CASE WHEN PDI_SALESAMT=0 THEN 100 ELSE CONVERT(INT,(((PDI_SALESAMT - VC_SALESAMT) / PDI_SALESAMT)*100)) END AS SLS_VAR_PCT
    --INTO TRC.SALES_TRACING_VAR
    FROM
    (
      select SALES_PERIOD, DIST_NR , DIST_ID , 
      COUNT(*) PDI_REC_CNT,
      CAST(sum(isnull(UPD_CS_QTY,0)) AS DECIMAL(18,2)) as PDI_QtySold,
      CAST(sum(isnull(UPD_SALES_AMT,0)) AS DECIMAL(18,2)) as PDI_SALESAMT
      from PDI_SALESTRACING_DEV.STAGE.SALES_TRACING_CURR
      where  SLS_CALC_STAT <> 'N'
      --  AND sales_period = ISNULL(@vSales_Period,sales_period) 
      --  AND DIST_NR = ISNULL(@vDist_NR,DIST_NR)
      
      group by SALES_PERIOD, DIST_NR ,  DIST_ID 
    ) PDI
    JOIN
    (   
      select SALESPERIOD, DISTCOID AS DIST_NR , DISTID, 
      COUNT(*) VC_REC_CNT,
      CAST(sum(isnull(COQTYSOLD,0)) AS DECIMAL(18,2)) as VC_QtySold,
      CAST(sum(isnull(COTOTALSALESAMNT,0)) AS DECIMAL(18,2)) as VC_SALESAMT 
      from PDI_SALESTRACING_DEV.STAGE.DDS_PDI_SAF_EXTRACT
      --where salesperiod = ISNULL(@vSales_Period ,salesperiod) 
      --  AND DISTCOID = ISNULL(@vDist_NR,DISTCOID)
      group by SALESPERIOD, DISTCOID, DISTID
    ) VC
    ON PDI.SALES_PERIOD = VC.SALESPERIOD AND  PDI.DIST_NR  = VC.DIST_NR;
  

  
END
GO
GRANT EXECUTE
    ON OBJECT::[STAGE].[spSALES_TRACING_VAR] TO [NICEPAK\Sajal.Dutta]
    AS [dbo];

