CREATE PROCEDURE [STAGE].[spTRC_VLDTN_LOAD_REF_TABLE]
WITH EXEC AS CALLER
AS
BEGIN

-- UPDATE LIST PRICE FROM FTPOUT LIST PRICE TABLE --

UPDATE L
SET L.CS_PRICE = F.LIST_PRICE,
L.BX_PRICE = F.LIST_PRICE/L.BX,
L.EA_PRICE = F.LIST_PRICE/L.EA,
L.[EFF DATE] = YEAR(F.EFF_DATE)*10000+MONTH(F.EFF_DATE)*100+DAY(F.EFF_DATE),
L.[EXP DATE] = YEAR(F.EXP_DATE)*10000+MONTH(F.EXP_DATE)*100+DAY(F.EXP_DATE)
FROM STAGE.LIST_PRICE L
JOIN FTPOUT.CompanyPriceListImport F ON L.[ITEM NO] = F.ITEM_NO;

--- Prepare the Distributor Price List 
TRUNCATE TABLE [STAGE].[Dist_Price];  -- MAKE A MERGE STATEMENT LATER

INSERT INTO [STAGE].[Dist_Price] (
[DISTID],[ITEMID],[EFFDATE],[EXPDATE],[CS_PRICE],[BX_PRICE],[EA_PRICE])
SELECT
[DISTID],[ITEMID],
YEAR([EFFDATE])*10000+MONTH([EFFDATE])*100+DAY([EFFDATE]) AS [EFFDATE],
YEAR([EXPDATE])*10000+MONTH([EXPDATE])*100+DAY([EXPDATE]) AS [EXPDATE],
[DISTLISTPRICE] AS CS_PRICE, 
([DISTLISTPRICE]/BX) AS BX_PRICE, ([DISTLISTPRICE]/EA) AS EA_PRICE
FROM [FTPOUT].[DistPriceListImport] D
JOIN [STAGE].[LIST_PRICE] L ON D.ITEMID = L.[ITEM NO];

--- Load Contract Table

TRUNCATE TABLE [STAGE].[CONT_PRICE];

INSERT INTO [STAGE].[CONT_PRICE]
([Contract ID],ITEMID,[Eff Date],[Exp Date],
[nEff Date],[nExp Date],[Contract Price])
SELECT 
CONTID AS [Contract ID], ITEMID, CONTITEMEFFDATE,CONTITEMEXPDATE,
YEAR(CONTITEMEFFDATE)*10000+MONTH(CONTITEMEFFDATE)*100+DAY(CONTITEMEFFDATE) AS [nEff Date], 
YEAR(CONTITEMEXPDATE)*10000+MONTH(CONTITEMEXPDATE)*100+DAY(CONTITEMEXPDATE) AS [nExp Date], 
CONTCOST AS [Contract Price]
FROM FTPOUT.ContractItemsImport;

END