CREATE PROCEDURE [STAGE].[spUniq_Flag] 
WITH EXEC AS CALLER
AS
BEGIN  

  UPDATE STAGE.DHC_COMPANY
    SET UNIQ_FLAG = NULL;
 
    UPDATE D1
      SET UNIQ_FLAG = 1 
    FROM STAGE.DHC_COMPANY D1,
    ( SELECT DHC_CO_ADDR_1,  DHC_CO_ZIP, COUNT(*)  CNT
      FROM STAGE.DHC_COMPANY
      WHERE DHC_CO_ADDR_2 IS NULL
      GROUP BY DHC_CO_ADDR_1, DHC_CO_ZIP
      HAVING COUNT(*) = 1) D2
    WHERE D1.DHC_CO_ADDR_1 = D2.DHC_CO_ADDR_1
      AND D1.DHC_CO_ZIP = D2.DHC_CO_ZIP
      AND DHC_CO_ADDR_2 IS NULL;
      
    --Assigning address uniqueness to DHC

    UPDATE D1
      SET UNIQ_FLAG = 2
    FROM STAGE.DHC_COMPANY D1,
    (SELECT DHC_CO_ADDR_1, DHC_CO_ADDR_2,  DHC_CO_ZIP, COUNT(*)  CNT
    FROM STAGE.DHC_COMPANY
    WHERE DHC_CO_ADDR_2 IS NOT NULL AND UNIQ_FLAG IS NULL
    GROUP BY DHC_CO_ADDR_1, DHC_CO_ADDR_2,DHC_CO_ZIP
    HAVING COUNT(*) = 1) D2
    WHERE D1.DHC_CO_ADDR_1 = D2.DHC_CO_ADDR_1
    AND D1.DHC_CO_ADDR_2 = D2.DHC_CO_ADDR_2
    AND D1.DHC_CO_ZIP = D2.DHC_CO_ZIP
    AND D1.DHC_CO_ADDR_2 IS NOT NULL
    AND D1.UNIQ_FLAG IS NULL;



    UPDATE D1
      SET UNIQ_FLAG = 12
    FROM STAGE.DHC_COMPANY D1,
    (SELECT DHC_CO_ADDR_1, DHC_CO_ADDR_2,  DHC_CO_ZIP, COUNT(*)  CNT
    FROM STAGE.DHC_COMPANY
    WHERE DHC_CO_ADDR_2 IS NOT NULL AND UNIQ_FLAG IS NULL
    GROUP BY DHC_CO_ADDR_1, DHC_CO_ADDR_2,DHC_CO_ZIP
    HAVING COUNT(*) > 1) D2
    WHERE D1.DHC_CO_ADDR_1 = D2.DHC_CO_ADDR_1
    AND D1.DHC_CO_ADDR_2 = D2.DHC_CO_ADDR_2
    AND D1.DHC_CO_ZIP = D2.DHC_CO_ZIP
    AND D1.DHC_CO_ADDR_2 IS NOT NULL
    AND D1.UNIQ_FLAG IS NULL;

    UPDATE D1
      SET UNIQ_FLAG = 11
    FROM STAGE.DHC_COMPANY D1,
    (SELECT DHC_CO_ADDR_1,   DHC_CO_ZIP, COUNT(*)  CNT
    FROM STAGE.DHC_COMPANY
    WHERE DHC_CO_ADDR_2 IS NULL AND UNIQ_FLAG IS NULL
    GROUP BY DHC_CO_ADDR_1, DHC_CO_ZIP
    HAVING COUNT(*) > 1) D2
    WHERE D1.DHC_CO_ADDR_1 = D2.DHC_CO_ADDR_1
    AND D1.DHC_CO_ZIP = D2.DHC_CO_ZIP
    AND D1.DHC_CO_ADDR_2 IS NULL
    AND D1.UNIQ_FLAG IS NULL;

  END;