CREATE PROCEDURE [STAGE].[spUpdate_SalesPeriod]
@Load_ID INT, @SALES_PERIOD VARCHAR(10)
WITH EXEC AS CALLER
AS
BEGIN
  
   UPDATE [STAGE].[SLS_TRC_LOAD_DTL] SET SALES_PERIOD = @SALES_PERIOD WHERE LOAD_ID = @Load_ID;
   
   UPDATE [STAGE].[SALES_TRACING_CURR] SET SALES_PERIOD = @SALES_PERIOD WHERE LOAD_ID = @Load_ID; 
END