CREATE PROCEDURE [STAGE].[spVar_Inv]
@vSales_Period varchar(10)=NULL, @vDist_NR varchar(48) = null
WITH EXEC AS CALLER
AS
BEGIN

TRUNCATE TABLE [TRC].[SALES_TRACING_VAR_INV];

  INSERT INTO  [TRC].[SALES_TRACING_VAR_INV]
      ( SALES_PERIOD, DIST_NR, DIST_ID, DIST_CNT_NR, DIST_PROD_ID, PDI_CNT_NR, PDI_PROD_ID, VC_CNT_NR, VC_PROD_ID, PDI_INV_ID, VC_INV_ID, PDI_INV_DT, VC_INV_DT, PDI_QtySold, VC_QtySold, PDI_SALESAMT, VC_SALESAMT, VAR_QTY_SOLD, VAR_SALES_AMT,PDI_PRC, VC_PRC )   
      
  SELECT PDI.SALES_PERIOD, PDI.DIST_NR ,  PDI.DIST_ID,
    PDI.DIST_CNT_NR, PDI.DIST_PROD_ID, PDI.PDI_CNT_NR, PDI.PDI_PROD_ID,
    VC_CNT_NR, VC.VC_PROD_ID, PDI.INV_ID, VC.DISTINVOICEID ,PDI.INV_DT_NR,VC.DISTINVOICEDATE,  
    PDI_QtySold,VC_QtySold,PDI_SALESAMT,VC_SALESAMT,
    (PDI_QtySold - VC_QtySold) AS VAR_QTY_SOLD,
    (PDI_SALESAMT - VC_SALESAMT) AS VAR_SALES_AMT,
    CASE WHEN ISNULL(PDI_QtySold,0) <> 0 THEN (PDI_SALESAMT/PDI_QtySold) ELSE NULL END AS PDI_PRC, 
    CASE WHEN ISNULL(VC_QtySold,0) <> 0 THEN (VC_SALESAMT/VC_QtySold) ELSE NULL END AS VC_PRC
    FROM
    (
      select SALES_PERIOD, DIST_NR ,  DIST_ID , INV_ID, INV_DT_NR, 
      ISNULL(TRC_CNT_ID,'NA') AS DIST_CNT_NR, TRC_PROD_ID AS DIST_PROD_ID,  
      ISNULL(UPD_CNT_ID,'NA') AS PDI_CNT_NR, UPD_PROD_ID AS PDI_PROD_ID,  
      CAST(sum(isnull(UPD_CS_QTY,0)) AS DECIMAL(18,2)) as PDI_QtySold,
      CAST(sum(isnull(UPD_SALES_AMT,0)) AS DECIMAL(18,2)) as PDI_SALESAMT
      from PDI_SALESTRACING_DEV.STAGE.SALES_TRACING_CURR
      where  
        sales_period = ISNULL(@vSales_Period,sales_period) 
        AND DIST_NR = ISNULL(@vDist_NR,DIST_NR)
        AND DIST_NR  NOT IN ('131043','60652','38921')
        AND SALES_PERIOD BETWEEN 20180701 AND 20190201
      AND SLS_CALC_STAT <> 'N'
      group by SALES_PERIOD, DIST_NR ,  DIST_ID ,INV_ID, INV_DT_NR,  
      TRC_CNT_ID, TRC_PROD_ID, UPD_CNT_ID, UPD_PROD_ID
    ) PDI
    full OUTER JOIN
    (
      select SALESPERIOD, DISTCOID AS DIST_NR , DISTID, DISTINVOICEID , DISTINVOICEDATE,
      ISNULL(DISTCONTID,'NA') AS DIST_CNT_NR, DISTITEMID AS DIST_PROD_ID,
      COCONTID AS VC_CNT_NR, COITEMID AS VC_PROD_ID,
      --convert(decimal,sum(COQTYSOLD),2) as VC_QtySold,
      CAST(sum(isnull(COQTYSOLD,0)) AS DECIMAL(18,2)) as VC_QtySold,
      CAST(sum(isnull(COTOTALSALESAMNT,0)) AS DECIMAL(18,2)) as VC_SALESAMT 
      from PDI_SALESTRACING_DEV.STAGE.DDS_PDI_SAF_EXTRACT
      where 
        salesperiod = ISNULL(@vSales_Period ,salesperiod) 
        AND DISTCOID = ISNULL(@vDist_NR,DISTCOID)
        AND DISTCOID NOT IN ('131043','60652','38921')
        AND SALESPERIOD BETWEEN 20180701 AND 20190201
      group by SALESPERIOD, DISTCOID, DISTID,DISTINVOICEID ,DISTINVOICEDATE, DISTCONTID, DISTITEMID,COCONTID,COITEMID
    ) VC
    ON PDI.SALES_PERIOD = VC.SALESPERIOD AND  PDI.DIST_NR  = VC.DIST_NR AND PDI.DIST_CNT_NR = VC.DIST_CNT_NR AND PDI.DIST_PROD_ID = VC.DIST_PROD_ID
    AND PDI.INV_ID = VC.DISTINVOICEID 
    ;
   

  
  UPDATE V
  SET V.CORR_PRC = C.PROD_PRC
  FROM [TRC].[SALES_TRACING_VAR_INV] V JOIN CNT.CNT_PROD C ON V.PDI_CNT_NR = C.CNT_NR AND V.PDI_PROD_ID = C.PROD_ID
  WHERE C.REC_STAT_CD = 'A'
  AND V.PDI_CNT_NR <> 'NA'
  AND V.CORR_PRC IS NULL;
  
  UPDATE V
  SET V.CORR_PRC = D.CS_PRICE
  FROM [TRC].[SALES_TRACING_VAR_INV] V JOIN STAGE.DIST_PRICE D ON D.ITEMID = V.PDI_PROD_ID AND D.DISTID = V.SALES_PERIOD
  WHERE V.PDI_CNT_NR ='NA'
  AND V.SALES_PERIOD BETWEEN D.EFFDATE AND D.EXPDATE
  AND V.CORR_PRC IS NULL;
  
  
  UPDATE V
  SET V.CORR_PRC = L.CS_PRICE
  FROM [TRC].[SALES_TRACING_VAR_INV] V JOIN STAGE.LIST_PRICE L ON V.PDI_PROD_ID = L.[ITEM NO]
  WHERE V.PDI_CNT_NR ='NA'
  AND V.CORR_PRC IS NULL;
  
  UPDATE [TRC].[SALES_TRACING_VAR_INV]
  SET ISSUE_WITH = 'TBD', ISSUE = 'QUANTITY'
  WHERE (PDI_QtySold < -1.02*VC_QtySold OR PDI_QtySold > 1.02*VC_QtySold) ;
  
  
  UPDATE [TRC].[SALES_TRACING_VAR_INV]
  SET ISSUE_WITH = 'PDI', ISSUE = CASE WHEN ISSUE IS NULL THEN 'PRICE' ELSE ISSUE+'; '+'PRICE' END
  WHERE VC_PRC BETWEEN -1.01*CORR_PRC AND 1.01*CORR_PRC
  AND (PDI_PRC < -1.01*CORR_PRC OR PDI_PRC > 1.01*CORR_PRC);
  
  UPDATE [TRC].[SALES_TRACING_VAR_INV]
  SET ISSUE_WITH = 'VC', ISSUE = CASE WHEN ISSUE IS NULL THEN 'PRICE' ELSE ISSUE+'; '+'PRICE' END
  WHERE PDI_PRC BETWEEN -1.01*CORR_PRC AND 1.01*CORR_PRC
  AND (VC_PRC < -1.01*CORR_PRC OR VC_PRC > 1.01*CORR_PRC);

  
END