CREATE TABLE [REPORT].[DIM_ENDUSER] (
    [ENDUSER_KEY]                         INT           NOT NULL,
    [ENDUSER_ID]                          VARCHAR (150) NOT NULL,
    [ENDUSER_SOURCE_TYPE]                 CHAR (6)      NOT NULL,
    [ENDUSER_NAME]                        VARCHAR (150) NULL,
    [ENDUSER_ADDR1]                       VARCHAR (100) NULL,
    [ENDUSER_ADDR2]                       VARCHAR (100) NULL,
    [ENDUSER_ADDR3]                       VARCHAR (50)  NULL,
    [ENDUSER_CITY]                        VARCHAR (50)  NULL,
    [ENDUSER_STATE]                       VARCHAR (50)  NULL,
    [ENDUSER_ZIP]                         NCHAR (20)    NULL,
    [ENDUSER_COUNTRY]                     VARCHAR (100) NULL,
    [HIN_NO]                              VARCHAR (20)  NULL,
    [DEA_NO]                              VARCHAR (20)  NULL,
    [GLN_NO]                              VARCHAR (20)  NULL,
    [MAX_COMPANY_TYPE]                    VARCHAR (50)  NULL,
    [DDS_COMPANY_TYPE]                    VARCHAR (50)  NULL,
    [PDI_COMPANY_TYPE]                    VARCHAR (50)  NULL,
    [L1_IDN_ID]                           VARCHAR (50)  NULL,
    [L1_IDN_NAME]                         VARCHAR (150) NULL,
    [L1_IDN_TYPE]                         VARCHAR (50)  NULL,
    [L1_IDN_RELATIONSHIP_TYPE]            VARCHAR (20)  NULL,
    [L1_IDN_GPO_ID]                       VARCHAR (20)  NULL,
    [L1_IDN_GPO_NAME]                     VARCHAR (50)  NULL,
    [L2_IDN_ID]                           VARCHAR (50)  NULL,
    [L2_IDN_NAME]                         VARCHAR (150) NULL,
    [L2_IDN_TYPE]                         VARCHAR (50)  NULL,
    [L2_IDN_RELATIONSHIP_TYPE]            VARCHAR (20)  NULL,
    [L2_IDN_GPO_ID]                       VARCHAR (20)  NULL,
    [L2_IDN_GPO_NAME]                     VARCHAR (50)  NULL,
    [L3_IDN_ID]                           VARCHAR (50)  NULL,
    [L3_IDN_NAME]                         VARCHAR (150) NULL,
    [L3_IDN_TYPE]                         VARCHAR (50)  NULL,
    [L3_IDN_RELATIONSHIP_TYPE]            VARCHAR (20)  NULL,
    [L3_IDN_GPO_ID]                       VARCHAR (20)  NULL,
    [L3_IDN_GPO_NAME]                     VARCHAR (50)  NULL,
    [L1_ENDUSER_PARENT_ID]                VARCHAR (150) NULL,
    [L1_ENDUSER_PARENT_NAME]              VARCHAR (150) NULL,
    [L1_ENDUSER_PARENT_CITY]              VARCHAR (50)  NULL,
    [L1_ENDUSER_PARENT_PDI_TYPE]          VARCHAR (50)  NULL,
    [L1_ENDUSER_PARENT_RELATIONSHIP_TYPE] VARCHAR (20)  NULL,
    [L2_ENDUSER_PARENT_ID]                VARCHAR (150) NULL,
    [L2_ENDUSER_PARENT_NAME]              VARCHAR (150) NULL,
    [L2_ENDUSER_PARENT_CITY]              VARCHAR (50)  NULL,
    [L2_ENDUSER_PARENT_PDI_TYPE]          VARCHAR (50)  NULL,
    [L2_ENDUSER_PARENT_RELATIONSHIP_TYPE] VARCHAR (20)  NULL,
    [L3_ENDUSER_PARENT_ID]                VARCHAR (150) NULL,
    [L3_ENDUSER_PARENT_NAME]              VARCHAR (150) NULL,
    [L3_ENDUSER_PARENT_CITY]              VARCHAR (50)  NULL,
    [L3_ENDUSER_PARENT_PDI_TYPE]          VARCHAR (50)  NULL,
    [L3_ENDUSER_PARENT_RELATIONSHIP_TYPE] VARCHAR (20)  NULL,
    [MEDPRO_INDICATOR]                    VARCHAR (25)  NULL,
    [PRIMARY_GPO_KEY]                     SMALLINT      NULL,
    [PRIMARY_GPO_NAME]                    VARCHAR (50)  NULL,
    [PRIMARY_CONTRACT_NO]                 VARCHAR (20)  NULL,
    [PRIMARY_TIER_LEVEL]                  VARCHAR (20)  NULL,
    [PRIMARY_PRICING_GROUP]               VARCHAR (20)  NULL,
    [ENDUSER_GROUP_KEY]                   INT           NULL,
    [TERRITORY_ID]                        VARCHAR (20)  NULL,
    [TERRITORY_KEY]                       SMALLINT      NULL,
    [CURRENT_INDICATOR]                   VARCHAR (10)  NULL,
    [EFF_DATE]                            DATE          NULL,
    [EXP_DATE]                            DATE          NULL,
    [ETL_AUDIT_KEY]                       SMALLINT      NULL,
    [L1_IDN_STATE]                        VARCHAR (50)  NULL,
    [L1_IDN_CITY]                         VARCHAR (50)  NULL,
    [L2_IDN_CITY]                         VARCHAR (50)  NULL,
    [L3_IDN_CITY]                         VARCHAR (50)  NULL,
    [L2_IDN_STATE]                        VARCHAR (50)  NULL,
    [L3_IDN_STATE]                        VARCHAR (50)  NULL,
    [L1_ENDUSER_PARENT_STATE]             VARCHAR (50)  NULL,
    [L2_ENDUSER_PARENT_STATE]             VARCHAR (50)  NULL,
    [L3_ENDUSER_PARENT_STATE]             VARCHAR (50)  NULL,
    [ENDUSER_SALES_TYPE]                  VARCHAR (20)  NULL,
    [SUPERGROUP_ID]                       VARCHAR (50)  NULL,
    [SUPERGROUP_NAME]                     VARCHAR (150) NULL,
    [SUPERGROUP_CITY]                     VARCHAR (50)  NULL,
    [SUPERGROUP_STATE]                    VARCHAR (50)  NULL,
    [SUPERGROUP_GPO]                      VARCHAR (50)  NULL,
    [EU_MARKET_SEGMENT]                   VARCHAR (50)  NULL,
    [CURRENT TIMESTAMP]                   VARCHAR (50)  NULL
);

