CREATE PROCEDURE [CNT].[spDSPLY_PND_CNT_XFER]
WITH EXEC AS CALLER
AS
BEGIN

 SELECT DISTINCT C.CNT_UPD_TYP, C.CNT_NR, P.PROD_ID
    FROM [CNT].[CONTRACT_TST] C
    JOIN [STAGE].[TEMP_NEW_CONT] T ON C.CNT_NR = T.CNT_NR AND T.SRC_REC_LST_MOD_DT = C.SRC_REC_LST_MOD_DT
    JOIN CNT.CNT_PROD_TST P ON P.CNT_NR = C.CNT_NR 
    WHERE C.REC_STAT_CD = 'A' AND P.REC_STAT_CD = 'A'
  UNION ALL
  SELECT DISTINCT C.CNT_UPD_TYP, C.CNT_NR, 'ALL'
    FROM [CNT].[CONTRACT_TST] C
    JOIN [STAGE].[TEMP_UPDT_CONT_DT] T ON C.CNT_NR = T.CNT_NR AND T.SRC_REC_LST_MOD_DT = C.SRC_REC_LST_MOD_DT
    AND C.REC_STAT_CD = 'A' 
  UNION ALL
  SELECT DISTINCT C.CNT_UPD_TYP, C.CNT_NR, T.ITM_NR
    FROM [CNT].[CONTRACT_TST] C
    JOIN [STAGE].[TEMP_NEW_ITEM_EXIST_CONT] T ON C.CNT_NR = T.CNT_NR AND T.SRCE_REC_MOD_DT_NR = C.SRC_REC_LST_MOD_DT
    AND C.REC_STAT_CD = 'A'     
  UNION ALL
  SELECT DISTINCT C.CNT_UPD_TYP, C.CNT_NR, T.ITM_NR
    FROM [CNT].[CONTRACT_TST] C
    JOIN [STAGE].[TEMP_UPD_ITEM] T ON C.CNT_NR = T.CNT_NR AND T.SRCE_REC_MOD_DT_NR = C.SRC_REC_LST_MOD_DT
    AND C.REC_STAT_CD = 'A' 

END