
CREATE PROCEDURE [CNT].[spGET_CONTRACT_EB]
	@cntNr varchar(7)
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT DISTINCT c.CMPNY_ID AS COMPANY_ID
      ,c.SRC_CMPNY_ID
      ,c.CMPNY_NM  AS COMPANY_NM
      ,c.CMPNY_ADDR_1 AS ADDR_1
      ,c.CMPNY_CITY AS CITY
      ,c.CMPNY_ST AS ST
      ,c.CMPNY_ZIP AS ZIP
	  ,eb.cnt_nr
		,CONVERT(varchar, CAST( ROUND(cs.[TOTAL SALES PRIOR YEAR],0) AS money), 1) AS SALES_AMT,
		c.BUYER_INDICATOR as BI,
		cs.[TOTAL SALES PRIOR YEAR]
  FROM CMPNY.COMPANY c
  inner join CNT_DEV.CNT_EB eb on c.CMPNY_ID = eb.cmpny_Id
  LEFT JOIN CMPNY.CMPNY_SALES cs ON cs.CMPNY_ID = c.CMPNY_ID
where		 cnt_nr = @cntNr
ORDER BY cs.[TOTAL SALES PRIOR YEAR] desc

END
