
CREATE PROCEDURE [CNT].[spGET_NEW_CONTRACT_NUMBER]
	        
AS
BEGIN
	
	SET NOCOUNT ON;
	SELECT 'CNT'+try_CONVERT(VARCHAR(10),MAX(try_CONVERT(INT,REPLACE(CNT_NR,'CNT','')))+1) AS NEW_CNT_NR   FROM [CNT_DEV].[CONTRACT] WHERE CNT_NR like 'CNT%'

	END

