CREATE TABLE [REF].[LKUP_CD] (
    [LKUP_DOMAIN_CD]  VARCHAR (20) NULL,
    [LKUP_DOMAIN_DES] VARCHAR (50) NULL,
    [LKUP_CD]         VARCHAR (20) NULL,
    [LKUP_CD_DES]     VARCHAR (50) NULL,
    [CD_TYP]          VARCHAR (20) NULL
);

