CREATE TABLE [REF].[NAME_CORR] (
    [NM_VAR]     VARCHAR (50)  NULL,
    [NM_STD]     VARCHAR (400) NULL,
    [CAT]        VARCHAR (50)  NULL,
    [SUB_CAT]    VARCHAR (20)  NULL,
    [REC_ACT_IN] CHAR (1)      NULL
);

