CREATE TABLE [PROD].[PRODUCT] (
    [PRODUCT_ID_PK]        INT           IDENTITY (1, 1) NOT NULL,
    [PROD_ID]              VARCHAR (15)  NOT NULL,
    [PROD_EFF_DT]          VARCHAR (10)  NULL,
    [PROD_EXP_DT]          VARCHAR (10)  NULL,
    [REC_STAT_CD]          CHAR (1)      NULL,
    [PROD_DESC_ERP]        VARCHAR (255) NOT NULL,
    [PROD_EXTRA_DESC_ERP]  VARCHAR (255) NULL,
    [PROD_CATEGORY_ERP]    VARCHAR (100) NOT NULL,
    [PROD_SLS_CAT_ID]      VARCHAR (100) NOT NULL,
    [PROD_MKT_CAT_ID]      VARCHAR (100) NOT NULL,
    [PROD_BRAND]           VARCHAR (100) NOT NULL,
    [SALES_TYPE]           VARCHAR (100) NOT NULL,
    [NEW_PROD_IN]          CHAR (1)      NOT NULL,
    [SELL_UOM]             CHAR (3)      NOT NULL,
    [BPCS_CREATE_DATE]     VARCHAR (10)  NULL,
    [BPCS_LAST_MAINT_DATE] VARCHAR (10)  NULL,
    [CURRENT TIMESTAMP]    VARCHAR (50)  NOT NULL
);

