CREATE TABLE [dbo].[GPOxREF] (
    [CoAcctNum]         VARCHAR (MAX) NULL,
    [CoAcctID]          VARCHAR (MAX) NULL,
    [CoAcctShipName]    VARCHAR (MAX) NULL,
    [CoAcctShipAddr1]   VARCHAR (MAX) NULL,
    [CoAcctShipCity]    VARCHAR (MAX) NULL,
    [CoAcctShipState]   VARCHAR (MAX) NULL,
    [CoAcctShipZip]     VARCHAR (MAX) NULL,
    [DistID]            VARCHAR (MAX) NULL,
    [DistCoID]          VARCHAR (MAX) NULL,
    [DistName]          VARCHAR (MAX) NULL,
    [DistAcctNum]       VARCHAR (MAX) NULL,
    [DistAcctID]        VARCHAR (MAX) NULL,
    [DistAcctShipName]  VARCHAR (MAX) NULL,
    [DistAcctShipAddr1] VARCHAR (MAX) NULL,
    [DistAcctShipAddr2] VARCHAR (MAX) NULL,
    [DistAcctShipCity]  VARCHAR (MAX) NULL,
    [DistAcctShipState] VARCHAR (MAX) NULL,
    [DistAcctShipZip]   VARCHAR (MAX) NULL,
    [GroupID]           VARCHAR (MAX) NULL,
    [GroupName]         VARCHAR (MAX) NULL,
    [GroupAcctID]       VARCHAR (MAX) NULL,
    [GroupAltID]        VARCHAR (MAX) NULL,
    [GroupAcctName]     VARCHAR (MAX) NULL,
    [GroupAcctAddr1]    VARCHAR (MAX) NULL,
    [GroupAcctAddr2]    VARCHAR (MAX) NULL,
    [GroupAcctCity]     VARCHAR (MAX) NULL,
    [GroupAcctState]    VARCHAR (MAX) NULL,
    [GroupAcctZip]      VARCHAR (MAX) NULL,
    [EnrollmentDate]    VARCHAR (MAX) NULL,
    [TerminationDate]   DATE          NULL,
    [MaxID]             VARCHAR (MAX) NULL,
    [GPOLinkCreateDate] DATE          NULL,
    [GPOLinkModDate]    DATE          NULL
);

