CREATE TABLE [dbo].[SALES_TRACING_NON_EDI_ETL] (
    [MONTH]                CHAR (2)        NULL,
    [DAY]                  CHAR (2)        NULL,
    [SALES PERIOD]         VARCHAR (10)    NULL,
    [YEAR]                 CHAR (4)        NULL,
    [RPT Date]             DECIMAL (8)     NULL,
    [DISTID]               VARCHAR (48)    NULL,
    [DIST NO]              VARCHAR (15)    NULL,
    [TRC Trans Type]       CHAR (2)        NULL,
    [TRC Contract ID]      VARCHAR (30)    NULL,
    [TRC Prod ID]          VARCHAR (48)    NULL,
    [TRC Price Type]       CHAR (4)        NULL,
    [Invoice ID]           VARCHAR (30)    NULL,
    [Invoice Date]         DATE            NULL,
    [nInvoice Date]        DECIMAL (10)    NULL,
    [TRC Unit]             CHAR (3)        NULL,
    [TRC Qty Sold]         DECIMAL (38)    NULL,
    [TRC Contract Price]   DECIMAL (38, 8) NULL,
    [TRC List Price]       DECIMAL (38, 8) NULL,
    [TRC Dist Price]       DECIMAL (38, 8) NULL,
    [TRC Rebate Amount]    DECIMAL (38, 8) NULL,
    [Line_Nr]              SMALLINT        NULL,
    [ShipTo_CD]            VARCHAR (20)    NULL,
    [ShipTo_NM]            VARCHAR (200)   NULL,
    [ShipTo_ADD1]          VARCHAR (100)   NULL,
    [ShipTo_ADD2]          VARCHAR (100)   NULL,
    [ShipTo_City]          VARCHAR (100)   NULL,
    [ShipTo_ST]            VARCHAR (10)    NULL,
    [ShipTo_Zip]           VARCHAR (12)    NULL,
    [ShipTo_Type]          VARCHAR (100)   NULL,
    [EndUser_CD]           VARCHAR (20)    NULL,
    [EndUser_NM]           VARCHAR (200)   NULL,
    [EndUser_ADD1]         VARCHAR (150)   NULL,
    [EndUser_ADD2]         VARCHAR (150)   NULL,
    [EndUser_City]         VARCHAR (100)   NULL,
    [EndUser_ST]           VARCHAR (10)    NULL,
    [EndUser_ZIP]          VARCHAR (12)    NULL,
    [EndUser_TYPE]         VARCHAR (100)   NULL,
    [Debit_Memo]           VARCHAR (40)    NULL,
    [CURRENT TIMESTAMP]    VARCHAR (50)    DEFAULT (getdate()) NOT NULL,
    [Updated Contract ID]  VARCHAR (30)    NULL,
    [Updated Prod ID]      VARCHAR (48)    NULL,
    [TRC CS PRICE]         DECIMAL (38, 8) NULL,
    [CONT Exp Date]        DATE            NULL,
    [TRC Updated Unit]     CHAR (2)        NULL,
    [Updated CS Qty]       DECIMAL (38, 8) NULL,
    [Updated CS Price]     DECIMAL (38, 4) NULL,
    [TRC Sales Amt]        DECIMAL (38, 8) NULL,
    [Updated Sales Amt]    DECIMAL (38, 8) NULL,
    [TRC Variance]         DECIMAL (38, 8) NULL,
    [REBATE_STATUS_CD]     CHAR (3)        NULL,
    [Updated Rebate Amt]   DECIMAL (38, 8) NULL,
    [SALES_CALC_IN]        CHAR (1)        NULL,
    [RBT Contract ID]      VARCHAR (30)    NULL,
    [Updated Price Type]   CHAR (4)        NULL,
    [TRC UPDATED CS PRICE] DECIMAL (38, 4) NULL,
    [ERROR CODE]           VARCHAR (40)    NULL,
    [LIST CS Price]        DECIMAL (38, 4) NULL,
    [CNT_EXP_DAYS]         INT             NULL,
    [CALC_STAT]            CHAR (1)        NULL,
    [UPDT_CNT_PRC]         FLOAT (53)      NULL,
    [UPDT_DIST_PRC]        FLOAT (53)      NULL,
    [UPDT_LIST_PRC]        FLOAT (53)      NULL,
    [INV_DT_IN]            CHAR (1)        NULL
);

