CREATE TABLE [dbo].[Sheet1$] (
    [USER_NM]   NVARCHAR (255) NULL,
    [GREET_NM]  NVARCHAR (255) NULL,
    [USER_ID]   NVARCHAR (255) NULL,
    [PWD]       NVARCHAR (255) NULL,
    [EMAIL]     NVARCHAR (255) NULL,
    [PCM_ROLE]  NVARCHAR (255) NULL,
    [ORG_ROLE]  NVARCHAR (255) NULL,
    [TERR_ID]   NVARCHAR (255) NULL,
    [REGION_ID] NVARCHAR (255) NULL
);

