CREATE TABLE [dbo].[Temp_Amerinet] (
    [Status]                NVARCHAR (255) NULL,
    [Intalere Facility #]   FLOAT (53)     NULL,
    [Parent Facility]       NVARCHAR (255) NULL,
    [Facility Name]         NVARCHAR (255) NULL,
    [Facility Contact Info] NVARCHAR (255) NULL,
    [Tier]                  NVARCHAR (255) NULL,
    [Contract #]            NVARCHAR (255) NULL,
    [Class of Trade]        NVARCHAR (255) NULL,
    [Primary Distributor]   NVARCHAR (255) NULL,
    [DEA #]                 NVARCHAR (255) NULL,
    [GLN/HIN]               NVARCHAR (255) NULL,
    [Signed Date]           DATETIME       NULL,
    [Sent Date]             DATETIME       NULL,
    [Address 1]             NVARCHAR (255) NULL,
    [Address 2]             NVARCHAR (255) NULL,
    [City]                  NVARCHAR (255) NULL,
    [State]                 NVARCHAR (255) NULL,
    [Zip Code]              NVARCHAR (255) NULL,
    [Comments]              NVARCHAR (255) NULL,
    [Activation Date]       DATETIME       NULL,
    [Intalere Contract #]   NVARCHAR (255) NULL,
    [Original Form]         NVARCHAR (255) NULL,
    [Parent]                NVARCHAR (255) NULL
);

