CREATE TABLE [dbo].[Temp_Vizient] (
    [MemberID]              FLOAT (53)     NULL,
    [LIC]                   NVARCHAR (255) NULL,
    [Member Name]           NVARCHAR (255) NULL,
    [Address1]              NVARCHAR (255) NULL,
    [City]                  NVARCHAR (255) NULL,
    [State]                 NVARCHAR (255) NULL,
    [Zip]                   NVARCHAR (255) NULL,
    [Contract Number]       NVARCHAR (255) NULL,
    [Pre-Slotted Tier]      FLOAT (53)     NULL,
    [Price Effective Date]  DATETIME       NULL,
    [Price Exp Date]        DATETIME       NULL,
    [System]                NVARCHAR (255) NULL,
    [Distributor ]          NVARCHAR (255) NULL,
    [Distributor 2]         NVARCHAR (255) NULL,
    [Phone Number]          NVARCHAR (255) NULL,
    [Region]                NVARCHAR (255) NULL,
    [Territory]             NVARCHAR (255) NULL,
    [Alliance Code]         NVARCHAR (255) NULL,
    [System ID]             FLOAT (53)     NULL,
    [Parent ID]             FLOAT (53)     NULL,
    [PA #]                  NVARCHAR (255) NULL,
    [Total Sales]           FLOAT (53)     NULL,
    [Bleach Sales]          FLOAT (53)     NULL,
    [Parent]                NVARCHAR (255) NULL,
    [Total Sales1]          FLOAT (53)     NULL,
    [Bleach Sales1]         FLOAT (53)     NULL,
    [Region1]               NVARCHAR (255) NULL,
    [Total Sales2]          FLOAT (53)     NULL,
    [Bleach Sales2]         FLOAT (53)     NULL,
    [Network]               NVARCHAR (255) NULL,
    [Total Sales3]          FLOAT (53)     NULL,
    [Commitment Program ID] FLOAT (53)     NULL,
    [GLN]                   NVARCHAR (255) NULL,
    [DEA]                   NVARCHAR (255) NULL,
    [HIN]                   NVARCHAR (255) NULL,
    [Bleach Sales3]         FLOAT (53)     NULL,
    [AMC]                   NVARCHAR (255) NULL,
    [Tier Confirmed]        NVARCHAR (255) NULL,
    [Comments from Field]   NVARCHAR (255) NULL,
    [Comment]               NVARCHAR (255) NULL
);

