CREATE PROCEDURE [MDM].[spDISPLAY_TERR]
WITH EXEC AS CALLER
AS
BEGIN

  SELECT DISTINCT T.TERRITORY_ID, T.TERRITORY_NAME 
 FROM STAGE.DIM_TERRITORY T
 WHERE T.CURRENT_INDICATOR_YN = 'Y'
 AND T.TERRITORY_ID NOT IN ('0', '999')
 ORDER BY 2
 
END