CREATE PROCEDURE [MDM].[spTRC_SAVE_CO_USR_FEEDBK]
@FEEDBK CHAR(1), @FEEDBK_ID INT
WITH EXEC AS CALLER
AS
BEGIN

  UPDATE PDI_SALESTRACING_DEV.MDM.USR_FEEDBK_CO
  SET USR_FEEDBK_CD =  @FEEDBK
  WHERE
  USER_FEEDBK_CO_ID = @FEEDBK_ID

END