CREATE TABLE [CMPNY].[COMPANY] (
    [CMPNY_ID]           INT             IDENTITY (7000001, 1) NOT NULL,
    [SRC_CMPNY_ID]       INT             NULL,
    [CMPNY_NM]           VARCHAR (255)   NOT NULL,
    [CMPNY_ALT_NM]       VARCHAR (255)   NULL,
    [ALT_NM_TYP]         VARCHAR (20)    NULL,
    [CMPNY_ADDR_1]       VARCHAR (255)   NULL,
    [CMPNY_ADDR_2]       VARCHAR (255)   NULL,
    [CMPNY_CITY]         VARCHAR (255)   NULL,
    [CMPNY_ST]           CHAR (2)        NULL,
    [CMPNY_ZIP]          VARCHAR (10)    NULL,
    [CMPNY_CNTRY]        CHAR (3)        NULL,
    [CMPNY_TYP_ID]       SMALLINT        NULL,
    [CMPNY_CTGRY_ID]     SMALLINT        NULL,
    [CMPNY_SGMNT_ID]     SMALLINT        NULL,
    [CMPNY_SUB_SGMNT_ID] SMALLINT        NULL,
    [COMPANY_URL]        VARCHAR (255)   NULL,
    [NPI_NR]             VARCHAR (50)    NULL,
    [GLN_NR]             VARCHAR (50)    NULL,
    [HIN_NR]             VARCHAR (50)    NULL,
    [DEA_NR]             VARCHAR (50)    NULL,
    [DHC_STAT]           VARCHAR (40)    NULL,
    [ISSUE_FLG]          VARCHAR (20)    NULL,
    [SRC_ID]             INT             NULL,
    [REC_EFF_DT]         DATE            NULL,
    [REC_EXP_DT]         DATE            NULL,
    [REC_STAT_IN]        CHAR (1)        NULL,
    [suffix]             VARCHAR (20)    NULL,
    [CMPNY_PRNT_SRC_ID]  INT             NULL,
    [IDN_SRC_ID]         INT             NULL,
    [IDN_PRNT_SRC_ID]    INT             NULL,
    [CMPNY_PRNT_ID]      INT             NULL,
    [IDN_CMPNY_ID]       INT             NULL,
    [IDN_PRNT_CMPNY_ID]  INT             NULL,
    [CUST_IN]            CHAR (1)        NULL,
    [BUYER_INDICATOR]    CHAR (1)        NULL,
    [SALES_12MNTH]       DECIMAL (38, 2) NULL
);

