CREATE TABLE [CMPNY].[COMPANY_REL_TYPE] (
    [REL_TYP_ID]     SMALLINT      IDENTITY (1, 1) NOT NULL,
    [REL_SUB_TYP_CD] VARCHAR (10)  NULL,
    [REL_TYP_NM]     VARCHAR (50)  NOT NULL,
    [REL_TYP_DESC]   VARCHAR (255) NULL,
    [REC_EFF_DT]     DATE          NULL,
    [REC_EXP_DT]     DATE          NULL,
    [REC_STAT_IN]    CHAR (1)      NOT NULL
);

