CREATE TABLE [CMPNY].[COMPANY_SEGMENT] (
    [CMPNY_SGMNT_ID]    SMALLINT      IDENTITY (1, 1) NOT NULL,
    [CMPNY_SGMNT_NM]    VARCHAR (50)  NOT NULL,
    [CMPNY_SGMNT_DESC]  VARCHAR (255) NULL,
    [REC_EFF_DT]        DATE          NULL,
    [REC_EXP_DT]        DATE          NULL,
    [REC_STAT_IN]       CHAR (1)      NULL,
    [FACILITY_PRIORITY] SMALLINT      NULL
);

