CREATE TABLE [CMPNY].[USR_FEEDBK_CO] (
    [Record_Status]          NVARCHAR (MAX) NULL,
    [COACCTID_Output]        NVARCHAR (MAX) NULL,
    [COACCTSHIPNAME_Source]  VARCHAR (100)  NULL,
    [COACCTSHIPADDR1_Source] VARCHAR (100)  NULL,
    [COACCTSHIPADDR2_Source] VARCHAR (50)   NULL,
    [COACCTSHIPCITY_Source]  VARCHAR (100)  NULL,
    [COACCTSHIPSTATE_Source] VARCHAR (2)    NULL,
    [COACCTSHIPZIP_Source]   VARCHAR (10)   NULL,
    [COACCTSHIPNAME_Output]  NVARCHAR (MAX) NULL,
    [COACCTSHIPADDR1_Output] NVARCHAR (MAX) NULL,
    [COACCTSHIPADDR2_Output] NVARCHAR (MAX) NULL,
    [COACCTSHIPZIP_Output]   NVARCHAR (MAX) NULL,
    [COACCTSHIPCITY_Output]  NVARCHAR (MAX) NULL,
    [COACCTSHIPSTATE_Output] NVARCHAR (MAX) NULL,
    [USR_FEEDBK_CD]          CHAR (1)       NULL,
    [TERR_ID]                NVARCHAR (10)  NULL,
    [TERR_NM]                NVARCHAR (24)  NULL,
    [USER_FEEDBK_CO_ID]      INT            IDENTITY (500001, 1) NOT NULL
);

