CREATE TABLE [MDM_STAGE].[ELB_ADDR_PARTS] (
    [SRC_ID]  INT           NOT NULL,
    [ST_NR]   VARCHAR (100) NULL,
    [ST_NM]   VARCHAR (255) NULL,
    [ST_TYP]  VARCHAR (50)  NULL,
    [ST_DIR]  VARCHAR (50)  NULL,
    [ST_NR_2] VARCHAR (10)  NULL,
    [BLDG_NR] VARCHAR (10)  NULL,
    [FL_NR]   VARCHAR (10)  NULL,
    [STE_NR]  VARCHAR (10)  NULL,
    [DIR_1]   VARCHAR (4)   NULL,
    [ADDR_1]  VARCHAR (150) NULL,
    [ADDR_2]  VARCHAR (60)  NULL
);

