CREATE TABLE [FTPOUT].[ContractsImport] (
    [CONTID]          VARCHAR (50)  NOT NULL,
    [CONTDESCRIPTION] VARCHAR (255) NOT NULL,
    [CONTEFFDATE]     DATE          NOT NULL,
    [CONTEXPDATE]     DATE          NOT NULL,
    [GROUPCONTID]     VARCHAR (50)  NULL,
    [GROUPADMINFEE]   DECIMAL (4)   NULL,
    [TIERLEVEL]       VARCHAR (20)  NULL
);

