CREATE TABLE [FTPOUT].[E867HDR_DAILY_HIST] (
    [HDRCUS]            VARCHAR (20) NOT NULL,
    [HDRSEQ]            DECIMAL (10) NOT NULL,
    [VNDRPT]            VARCHAR (30) NULL,
    [RPTDTE]            DECIMAL (8)  NULL,
    [SALRPT]            CHAR (2)     NULL,
    [RPTEND]            CHAR (3)     NULL,
    [RBTDTE]            DECIMAL (8)  NULL,
    [SLSRGN]            CHAR (3)     NULL,
    [REGION]            VARCHAR (30) NULL,
    [SELDBT]            CHAR (3)     NULL,
    [DEBIT#]            VARCHAR (30) NULL,
    [BRCHDB]            VARCHAR (22) NULL,
    [BRANCH]            VARCHAR (30) NULL,
    [BRCHCD]            VARCHAR (22) NULL,
    [MFGMF]             CHAR (3)     NULL,
    [MANNAM]            VARCHAR (30) NULL,
    [MANCD]             VARCHAR (22) NULL,
    [RPTSTR]            CHAR (3)     NULL,
    [RPTSDTE]           DECIMAL (8)  NULL,
    [HISA06]            VARCHAR (15) NULL,
    [HISA13]            DECIMAL (9)  NOT NULL,
    [HST02]             DECIMAL (9)  NULL,
    [HSTAT]             CHAR (1)     NULL,
    [HSDTE]             DECIMAL (8)  NULL,
    [CURRENT TIMESTAMP] VARCHAR (50) NULL,
    CONSTRAINT [PK__E867HDR___DC38593365C34606] PRIMARY KEY CLUSTERED ([HDRCUS] ASC, [HDRSEQ] ASC, [HISA13] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [UQ__E867HDR___BC5ECDDA0831C594] UNIQUE NONCLUSTERED ([HDRCUS] ASC, [HDRSEQ] ASC) WITH (FILLFACTOR = 100)
);

