CREATE TABLE [FTPOUT].[E867DTL_DAILY_HIST] (
    [DTLCUS]            VARCHAR (20) NOT NULL,
    [DTLSEQ]            DECIMAL (10) NOT NULL,
    [DDLSEQ]            DECIMAL (10) NOT NULL,
    [PTDTYP]            CHAR (2)     NOT NULL,
    [CTRQUL]            CHAR (3)     NULL,
    [CTRNUM]            VARCHAR (22) NULL,
    [CTRREF]            CHAR (3)     NULL,
    [REFCDE]            VARCHAR (15) NULL,
    [CTRDSC]            VARCHAR (35) NULL,
    [BTID]              CHAR (3)     NULL,
    [BTNAME]            VARCHAR (50) NULL,
    [BTCODE]            VARCHAR (22) NULL,
    [BTADD1]            VARCHAR (50) NULL,
    [BTADD2]            VARCHAR (50) NULL,
    [BTCITY]            VARCHAR (50) NULL,
    [BTSTE]             CHAR (3)     NULL,
    [BTZIP]             VARCHAR (10) NULL,
    [STID]              CHAR (3)     NULL,
    [STNAME]            VARCHAR (50) NULL,
    [STCODE]            VARCHAR (22) NULL,
    [STADD1]            VARCHAR (50) NULL,
    [STADD2]            VARCHAR (50) NULL,
    [STCITY]            VARCHAR (50) NULL,
    [STSTE]             CHAR (3)     NULL,
    [STZIP]             VARCHAR (10) NULL,
    [REFGLN]            CHAR (3)     NULL,
    [GLNNUM]            VARCHAR (30) NULL,
    [GLNDSC]            VARCHAR (30) NULL,
    [REFDEA]            CHAR (3)     NULL,
    [DEANUM]            VARCHAR (30) NULL,
    [DEADSC]            VARCHAR (30) NULL,
    [REFHIN]            CHAR (3)     NULL,
    [HINNUM]            VARCHAR (30) NULL,
    [HINDSC]            VARCHAR (30) NULL,
    [REFMUT]            CHAR (3)     NULL,
    [MUTNUM]            VARCHAR (30) NULL,
    [MUTDSC]            VARCHAR (30) NULL,
    [DISA06]            VARCHAR (15) NOT NULL,
    [DISA13]            DECIMAL (9)  NOT NULL,
    [DST02]             DECIMAL (9)  NOT NULL,
    [CURRENT TIMESTAMP] VARCHAR (50) NOT NULL,
    CONSTRAINT [UQ__E867DTL___BE89999E5805B5E1] UNIQUE NONCLUSTERED ([DTLCUS] ASC, [DTLSEQ] ASC, [DDLSEQ] ASC) WITH (FILLFACTOR = 100)
);

