CREATE TABLE [FTPOUT].[E867SDTL_DAILY_HIST] (
    [SDTCUS]            VARCHAR (20)    NOT NULL,
    [SDDSEQ]            DECIMAL (10)    NOT NULL,
    [SDLSEQ]            DECIMAL (10)    NOT NULL,
    [SLLSEQ]            DECIMAL (10)    NOT NULL,
    [QTYSQL]            CHAR (2)        NOT NULL,
    [QTYSLD]            DECIMAL (15)    NOT NULL,
    [QTYSUM]            CHAR (3)        NOT NULL,
    [QTYOQL]            CHAR (2)        NOT NULL,
    [QTYORG]            DECIMAL (15)    NOT NULL,
    [QTYOUM]            CHAR (3)        NOT NULL,
    [QTYKQL]            CHAR (2)        NOT NULL,
    [QTYKRG]            DECIMAL (15)    NOT NULL,
    [QTYKUM]            CHAR (3)        NOT NULL,
    [QALCAT]            CHAR (2)        NOT NULL,
    [CATNUM]            VARCHAR (48)    NOT NULL,
    [QALSEL]            CHAR (2)        NOT NULL,
    [SELNUM]            VARCHAR (48)    NOT NULL,
    [CAUOM]             CHAR (3)        NOT NULL,
    [CAPRC]             DECIMAL (17, 3) NOT NULL,
    [CACDE]             CHAR (2)        NOT NULL,
    [CTUOM]             CHAR (3)        NOT NULL,
    [CTPRC]             DECIMAL (17, 3) NOT NULL,
    [CTCDE]             CHAR (2)        NOT NULL,
    [DIUOM]             CHAR (3)        NOT NULL,
    [DIPRC]             DECIMAL (17, 3) NOT NULL,
    [DICDE]             CHAR (2)        NOT NULL,
    [RSUOM]             CHAR (3)        NOT NULL,
    [RSPRC]             DECIMAL (17, 3) NOT NULL,
    [RSCDE]             CHAR (2)        NOT NULL,
    [AMTCTQ]            CHAR (3)        NOT NULL,
    [AMTCT$]            DECIMAL (17, 2) NOT NULL,
    [AMTCCQ]            CHAR (3)        NOT NULL,
    [AMTCC$]            DECIMAL (17, 2) NOT NULL,
    [REFCI]             CHAR (3)        NOT NULL,
    [CIDESC]            VARCHAR (30)    NOT NULL,
    [REFDI]             CHAR (3)        NOT NULL,
    [DIDESC]            VARCHAR (30)    NOT NULL,
    [REFIX]             CHAR (3)        NOT NULL,
    [IXDESC]            VARCHAR (30)    NOT NULL,
    [REFLI]             CHAR (3)        NOT NULL,
    [LIDESC]            VARCHAR (30)    NOT NULL,
    [REFPE]             CHAR (3)        NOT NULL,
    [PEDESC]            VARCHAR (30)    NOT NULL,
    [REFPO]             CHAR (3)        NOT NULL,
    [PODESC]            VARCHAR (30)    NOT NULL,
    [INVQAL]            CHAR (3)        NOT NULL,
    [INVDTE]            DECIMAL (8)     NOT NULL,
    [ORDQAL]            CHAR (3)        NOT NULL,
    [ORDDTE]            DECIMAL (8)     NOT NULL,
    [QALGTN]            CHAR (2)        NOT NULL,
    [GTNNUM]            VARCHAR (48)    NOT NULL,
    [RSVQAL]            CHAR (2)        NOT NULL,
    [RSVPRD]            VARCHAR (48)    NOT NULL,
    [REFBC]             CHAR (3)        NOT NULL,
    [BCDESC]            VARCHAR (30)    NOT NULL,
    [REFGLNO]           CHAR (3)        NOT NULL,
    [GLNDESC]           VARCHAR (30)    NOT NULL,
    [SISA06]            VARCHAR (15)    NOT NULL,
    [SISA13]            DECIMAL (9)     NOT NULL,
    [SST02]             DECIMAL (9)     NOT NULL,
    [CURRENT TIMESTAMP] VARCHAR (50)    NULL,
    CONSTRAINT [UQ__E867SDTL__882B3200A6435E4C] UNIQUE NONCLUSTERED ([SDTCUS] ASC, [SDDSEQ] ASC, [SDLSEQ] ASC, [SLLSEQ] ASC) WITH (FILLFACTOR = 100)
);

